"""
Django settings for polotskcge_vitebsk project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  #'www.polotskcge.by', 'polotskcge.by'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
    'tinymce',
    'news',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'polotskcge_vitebsk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'polotskcge_vitebsk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Добавляем подпапки "новости" и "вебапп" к пути статических файлов
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static', 'news'),
    os.path.join(BASE_DIR, 'static', 'webapp'),
]



TINYMCE_DEFAULT_CONFIG = {
    'plugins': (
        'advlist autolink lists link image charmap print preview anchor help '
        'searchreplace visualblocks code fullscreen '
        'insertdatetime media table paste wordcount '
        'textcolor colorpicker code fontfamily fontsize'
    ),
    'toolbar': (
        'undo redo | formatselect | '
        'fontfamily fontsize | '
        'bold italic underline forecolor backcolor | '
        'alignleft aligncenter alignright alignjustify | '
        'bullist numlist outdent indent | '
        'link image | code | removeformat | help'
    ),
    'height': 500,
    'menubar': False,
    'branding': False,
    'contextmenu': 'formats | link image | code',
    'content_style': 'body { font-family: Arial, sans-serif; font-size: 14px; }',
    'fontfamily_formats': "Andale Mono=andale mono,times; Arial=arial,helvetica,sans-serif; Arial Black=arial black,avant garde; Book Antiqua=book antiqua,palatino; Comic Sans MS=comic sans ms,sans-serif; Courier New=courier new,courier; Georgia=georgia,palatino; Helvetica=helvetica; Impact=impact,chicago; Lucida Console=lucida console,monaco; Lucida Sans Unicode=lucida sans unicode,lucida sans; Microsoft Sans Serif=microsoft sans serif,sans-serif; Monotype Corsiva=monotype corsiva,cursive; MS Sans Serif=ms sans serif,sans-serif; MS Serif=ms serif,sans-serif; Palatino=palatino; Tahoma=tahoma,arial,helvetica,sans-serif; Terminal=terminal,monaco; Times New Roman=times new roman,times; Trebuchet MS=trebuchet ms,geneva; Verdana=verdana,geneva; Webdings=webdings; Wingdings=wingdings,zapf dingbats",
    'fontsize_formats': "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
    'file_picker_callback': 'function (callback, value, meta) {'
                           'const input = document.createElement("input");'
                           'input.setAttribute("type", "file");'
                           'input.onchange = function () {'
                           'const file = input.files[0];'
                           'const reader = new FileReader();'
                           'reader.addEventListener("load", function () {'
                           'const id = "blobid" + (new Date()).getTime();'
                           'const blobCache = tinymce.activeEditor.editorUpload.blobCache;'
                           'const base64 = reader.result.split(",");'
                           'const blobInfo = blobCache.create(id, file, base64);'
                           'blobCache.add(blobInfo);'
                           'callback(blobInfo.blobUri(), { title: file.name });'
                           '});'
                           'reader.readAsDataURL(file);'
                           '};'
                           'input.click();'
                           '}',
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
CKEDITOR_UPLOAD_PATH = "uploads/"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
