# Generated by Django 5.0.3 on 2024-04-27 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('description_small', models.TextField(default='', max_length=500, verbose_name='Description_small')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('description_company', models.TextField(default='Описание для нижнего блока', verbose_name='Description_company')),
                ('location', models.CharField(default='', max_length=200, verbose_name='Location')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Photo')),
                ('logo_photo', models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Logo Photo')),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='author_photos/', verbose_name='Author Photo')),
                ('comment', models.TextField(default='Your default comment here', verbose_name='Comment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('comment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment Author')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
