# Generated by Django 5.0.3 on 2024-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Интерактитвное меню',
                'verbose_name_plural': 'Интерактитвное меню',
            },
        ),
    ]
