# Generated by Django 5.0.3 on 2024-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_interactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='description_two',
            field=models.TextField(default='', verbose_name='Второе Описание'),
        ),
    ]
