# Generated by Django 5.0.3 on 2024-04-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_previewnews_alter_interactive_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewnews',
            name='link',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
