# Generated by Django 5.0.3 on 2024-05-05 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_previewnews_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelnews',
            options={'verbose_name': 'Главная модель Новости', 'verbose_name_plural': 'Главная модель Новости'},
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos/', verbose_name='Фото автора'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='comment',
            field=models.TextField(default='Примечание', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='comment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментарий автора'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='description_company',
            field=models.TextField(default='Описание для нижнего блока', verbose_name='Описание для нижнего блока'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='description_small',
            field=models.TextField(default='', max_length=500, verbose_name='Не большое описание'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Место где (локация)'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='logo_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото(маленькое)'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата Публикации'),
        ),
        migrations.AlterField(
            model_name='modelnews',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
