# Generated by Django 5.0.3 on 2024-05-06 12:42

from django.db import migrations, models
from tinymce.models import HTMLField  # Импортируем HTMLField для использования с TinyMCE

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_modelnews_options_alter_modelnews_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео файл')),
                ('description', HTMLField(verbose_name='Краткое описание')),  # Заменяем CKEditor5Field на HTMLField
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('category', models.CharField(max_length=100, verbose_name='Название рубрики')),
            ],
            options={
                'verbose_name': 'Видео Новости',
                'verbose_name_plural': 'Видео Новости',
            },
        ),
    ]
