# Generated by Django 5.0.3 on 2024-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='На главный экран'),
        ),
    ]
