# Generated by Django 5.0.3 on 2024-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_video_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnews',
            name='is_nature_news',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новости о природе'),
        ),
        migrations.AddField(
            model_name='modelnews',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, verbose_name='Популярные'),
        ),
    ]
