# Generated by Django 5.0.3 on 2024-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_modelnews_is_economic_news_modelnews_is_health_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewnews',
            name='is_economic_news',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новости экономики'),
        ),
        migrations.AddField(
            model_name='previewnews',
            name='is_health_news',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новости о здоровье'),
        ),
        migrations.AddField(
            model_name='previewnews',
            name='is_main_news',
            field=models.BooleanField(blank=True, default=False, verbose_name='Важное'),
        ),
        migrations.AddField(
            model_name='previewnews',
            name='is_nature_news',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новости о природе'),
        ),
        migrations.AddField(
            model_name='previewnews',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, verbose_name='Популярные'),
        ),
        migrations.AddField(
            model_name='previewnews',
            name='is_sport_news',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новости спорта'),
        ),
    ]
