# Generated by Django 5.0.3 on 2024-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_previewnews_is_economic_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previewnews',
            name='link',
        ),
    ]
