# Generated by Django 5.0.3 on 2024-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_modelnews_is_main_days_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnews',
            name='is_city',
            field=models.BooleanField(blank=True, default=False, verbose_name='Города/Посёлки'),
        ),
    ]
