# Generated by Django 5.0.3 on 2025-01-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_modelnews_is_city'),
        ('webapp', '0235_alter_educationalresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnews',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='webapp.cities'),
        ),
    ]
