# Generated by Django 5.0.3 on 2025-01-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_modelnews_city'),
        ('webapp', '0241_delete_immunoprophylaxisinf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnews',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='webapp.cities'),
        ),
    ]
