# Generated by Django 5.0.3 on 2025-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_modelnews_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnews',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
