# Generated by Django 5.0.3 on 2025-01-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_modelnews_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelnews',
            name='is_published',
        ),
    ]
