# Generated by Django 5.0.3 on 2025-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_modelnews_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
