# Generated by Django 5.0.3 on 2025-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_modelnews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnews',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='URL-адрес'),
        ),
    ]
