# Generated by Django 5.0.3 on 2024-03-19 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=100)),
                ('head_doctor_first_name', models.CharField(default='John', max_length=100)),
                ('head_doctor_last_name', models.CharField(default='Doe', max_length=100)),
                ('head_doctor_position', models.CharField(default='Doctor', max_length=100)),
                ('head_doctor_phone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('position', models.CharField(default='Doctor', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='webapp.doctor'),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Jane', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('position', models.CharField(default='Nurse', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nurses/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
