# Generated by Django 5.0.3 on 2024-03-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_doctor_department_remove_nurse_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктора', 'verbose_name_plural': 'Доктора'},
        ),
    ]
