# Generated by Django 5.0.3 on 2024-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_doctor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Service Name', max_length=100)),
                ('description', models.TextField(default='Service Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_icons/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
