# Generated by Django 5.0.3 on 2024-03-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_services_title_alter_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_title',
            name='link',
        ),
    ]
