# Generated by Django 5.0.3 on 2024-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='description_li',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_li_five',
            field=models.CharField(default='About Us Name Li-Five', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_li_four',
            field=models.CharField(default='About Us Name Li-Four', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_li_one',
            field=models.CharField(default='About Us Name Li-One', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_li_three',
            field=models.CharField(default='About Us Name Li-Three', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_li_two',
            field=models.CharField(default='About Us Name Li-Two', max_length=100),
        ),
    ]
