# Generated by Django 5.0.3 on 2024-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_aboutus_description_li_aboutus_name_li_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
    ]
