# Generated by Django 5.0.3 on 2024-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_aboutus_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Researches Name One', max_length=100)),
                ('description', models.TextField(default='Researches Description One')),
                ('name_two', models.CharField(default='Researches Name Two', max_length=100)),
                ('description_two', models.TextField(default='Researches Description Two')),
                ('name_three', models.CharField(default='Researches Name Three', max_length=100)),
                ('description_three', models.TextField(default='Researches Description Three')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='researches/')),
            ],
            options={
                'verbose_name': 'Блок Иновации',
                'verbose_name_plural': 'Блок Иновации',
            },
        ),
    ]
