# Generated by Django 5.0.3 on 2024-03-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_researches'),
    ]

    operations = [
        migrations.AddField(
            model_name='researches',
            name='description_four',
            field=models.TextField(default='Researches Description Four'),
        ),
        migrations.AddField(
            model_name='researches',
            name='name_four',
            field=models.CharField(default='Researches Name Four', max_length=100),
        ),
    ]
