# Generated by Django 5.0.3 on 2024-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_researches_description_four_researches_name_four'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Service Name', max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_icons/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Лого на Главной',
                'verbose_name_plural': 'Лого на Главной',
            },
        ),
    ]
