# Generated by Django 5.0.3 on 2024-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(default='Logo Name', max_length=100),
        ),
    ]
