# Generated by Django 5.0.3 on 2024-04-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='researches',
            name='icon_class',
            field=models.CharField(default='bx bxs-flask', max_length=100),
        ),
    ]
