# Generated by Django 5.0.3 on 2024-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_researches_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='researches',
            name='icon_class_four',
            field=models.CharField(default='bx bxs-flask', max_length=100),
        ),
        migrations.AddField(
            model_name='researches',
            name='icon_class_three',
            field=models.CharField(default='bx bxs-flask', max_length=100),
        ),
        migrations.AddField(
            model_name='researches',
            name='icon_class_two',
            field=models.CharField(default='bx bxs-flask', max_length=100),
        ),
    ]
