# Generated by Django 5.0.3 on 2024-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_researches_icon_class_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='icon_class',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon_class_li_five',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon_class_li_four',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon_class_li_one',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon_class_li_three',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon_class_li_two',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
    ]
