# Generated by Django 5.0.3 on 2024-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_aboutus_icon_class_aboutus_icon_class_li_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='icon_class',
            field=models.CharField(default='fas fa-heartbeat', max_length=100),
        ),
    ]
