# Generated by Django 5.0.3 on 2024-04-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_featured_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('reception_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Часы приема',
                'verbose_name_plural': 'Часы приема',
            },
        ),
    ]
