# Generated by Django 5.0.3 on 2024-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_receptionhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionhours',
            name='family_name',
            field=models.CharField(default='Фамилия', max_length=100),
        ),
        migrations.AddField(
            model_name='receptionhours',
            name='last_name',
            field=models.CharField(default='Имя и Отчество', max_length=100),
        ),
    ]
