# Generated by Django 5.0.3 on 2024-04-10 11:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_receptionhours_family_name_receptionhours_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Общая информация',
                'verbose_name_plural': 'Общая информация',
            },
        ),
        migrations.AlterField(
            model_name='receptionhours',
            name='reception_time',
            field=models.CharField(default='Часы приёма', max_length=100),
        ),
        migrations.AddField(
            model_name='receptionhours',
            name='general_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_hours', to='webapp.generalinfo'),
        ),
    ]
