# Generated by Django 5.0.3 on 2024-04-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_question_alter_generalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='вопрос', max_length=255),
        ),
        migrations.AlterField(
            model_name='receptionhours',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_hours', to='webapp.generalinfo'),
        ),
    ]
