# Generated by Django 5.0.3 on 2024-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_question_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
