# Generated by Django 5.0.3 on 2024-04-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_answer_answer_text'),
    ]

    operations = [
    ]
