# Generated by Django 5.0.3 on 2024-04-10 13:11

from django.db import migrations, models
from tinymce.models import HTMLField  # Импортируем HTMLField для использования с TinyMCE

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20240410_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='description',
            field=HTMLField(default='Описание', blank=True, null=True, max_length=200),  # Заменяем CKEditor5Field на HTMLField
        ),
    ]
