# Generated by Django 5.0.3 on 2024-04-10 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20240410_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='description',
            field=ckeditor.fields.RichTextField(default='Описание', null=True, max_length=200),
        ),
    ]
