# Generated by Django 5.0.3 on 2024-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_generalinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='title',
            field=models.CharField(default='Тайтл', blank=True, null=True, max_length=100),
        ),
    ]
