# Generated by Django 5.0.3 on 2024-04-10 13:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_generalinfo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Ansver_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Заголовок', max_length=255)),
                ('description', ckeditor.fields.RichTextField(default='Описание', max_length=200)),
            ],
            options={
                'verbose_name': 'Заголовок и Описание Ответов',
                'verbose_name_plural': 'Заголовок и Описание Ответов',
            },
        ),
        migrations.AlterField(
            model_name='receptionhours',
            name='general_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_hours', to='webapp.generalinfo'),
        ),
    ]
