# Generated by Django 5.0.3 on 2024-04-27 12:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_question_ansver_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='description',
            field=ckeditor.fields.RichTextField(default='Описание', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='title',
            field=models.CharField(default='Тайтл', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_ansver_title',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_ansver_title',
            name='name',
            field=models.CharField(default='Заголовок', max_length=255),
        ),
        migrations.AlterField(
            model_name='receptionhours',
            name='general_info',
            field=models.ForeignKey(blank=True, default='Основная Инф', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception_hours', to='webapp.generalinfo'),
        ),
        migrations.AlterField(
            model_name='receptionhours',
            name='reception_time',
            field=models.CharField(default='Часы приёма', max_length=100),
        ),
    ]
