# Generated by Django 5.0.3 on 2024-04-15 14:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_question_ansver_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='description',
            field=ckeditor.fields.RichTextField(default='Описание', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='title',
            field=models.CharField(default='Тайтл', max_length=100),
        ),
        migrations.AlterField(
            model_name='receptionhours',
            name='general_info',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reception_hours', to='webapp.generalinfo'),
            preserve_default=False,
        ),
    ]
