# Generated by Django 5.0.3 on 2024-05-27 12:46

from django.db import migrations, models
from tinymce.models import HTMLField  # Используйте HTMLField для TinyMCE


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', HTMLField(verbose_name='Описание')),  # Замените CKEditor5Field на HTMLField
                ('pdf_file', models.FileField(upload_to='pdfs/', verbose_name='Прикрепить PDF')),
            ],
            options={
                'verbose_name': 'Образовательный ресурс',
                'verbose_name_plural': 'Образовательные ресурсы',
            },
        ),
    ]
