# Generated by Django 5.0.3 on 2024-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_educationalresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='icon_class',
            field=models.CharField(default='fas fa-heartbeat', max_length=100),
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='link',
            field=models.URLField(default='default_value', verbose_name='Прикрепить ссылку'),
            preserve_default=False,
        ),
    ]
