# Generated by Django 5.0.3 on 2024-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_remove_educationalresource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Публикации'),
        ),
    ]
