# Generated by Django 5.0.3 on 2024-05-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_educationalresource_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalresource',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Образовательный ресурс', 'verbose_name_plural': 'Образовательные ресурсы'},
        ),
    ]
