# Generated by Django 5.0.3 on 2024-05-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_alter_educationalresource_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalresource',
            name='icon_class',
            field=models.CharField(default='fas fa-file-pdf', max_length=100),
        ),
    ]
