# Generated by Django 5.0.3 on 2024-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_alter_educationalresource_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zoj Us Name One', max_length=100)),
                ('description', models.TextField(default='Zoj Us Description One')),
                ('name_two', models.CharField(default='Zoj Us Name Two', max_length=100)),
                ('description_two', models.TextField(default='Zoj Us Description Two')),
                ('name_li_one', models.CharField(default='Zoj Us Name Li-One', max_length=100)),
                ('name_li_two', models.CharField(default='Zoj Us Name Li-Two', max_length=100)),
                ('name_li_three', models.CharField(default='Zoj Us Name Li-Three', max_length=100)),
                ('name_li_four', models.CharField(default='Zoj Us Name Li-Four', max_length=100)),
                ('name_li_five', models.CharField(default='Zoj Us Name Li-Five', max_length=100)),
                ('description_three', models.TextField(default='Zoj Us Description Three')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Zoj/')),
                ('icon_class', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_one', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_two', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_three', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_four', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_five', models.CharField(default='bi bi-check-circle', max_length=100)),
            ],
            options={
                'verbose_name': 'Здоровый Образ Жизни',
                'verbose_name_plural': 'Здоровый Образ Жизни',
            },
        ),
    ]
