# Generated by Django 5.0.3 on 2024-05-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_zoj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoj',
            name='name_li_five',
            field=models.CharField(default='Zoj Us Name Li-Five', max_length=150),
        ),
        migrations.AlterField(
            model_name='zoj',
            name='name_li_four',
            field=models.CharField(default='Zoj Us Name Li-Four', max_length=150),
        ),
        migrations.AlterField(
            model_name='zoj',
            name='name_li_one',
            field=models.CharField(default='Zoj Us Name Li-One', max_length=150),
        ),
        migrations.AlterField(
            model_name='zoj',
            name='name_li_three',
            field=models.CharField(default='Zoj Us Name Li-Three', max_length=150),
        ),
        migrations.AlterField(
            model_name='zoj',
            name='name_li_two',
            field=models.CharField(default='Zoj Us Name Li-Two', max_length=150),
        ),
    ]
