# Generated by Django 5.0.3 on 2024-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_zoj_name_li_five_alter_zoj_name_li_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoj',
            name='photo_two',
            field=models.ImageField(blank=True, null=True, upload_to='Zoj/'),
        ),
    ]
