# Generated by Django 5.0.3 on 2024-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_zoj_photo_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Featured Name', max_length=100)),
                ('description', models.TextField(default='Featured Description')),
                ('icon_class', models.CharField(default='fas fa-heartbeat', max_length=100)),
            ],
            options={
                'verbose_name': 'Книга жалоб и предложений',
                'verbose_name_plural': 'Книга жалоб и предложений',
            },
        ),
    ]
