# Generated by Django 5.0.3 on 2024-06-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_remove_book_complaint_icon_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlineHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='Фамилия Имя и Отчество | Должность', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('reception_time', models.CharField(default='Время проведения прямой линии', max_length=100)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата Проведения прям линии')),
                ('phone_info', models.ForeignKey(blank=True, default='Информация о телефоне', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotline_hours', to='webapp.generalinfo')),
            ],
            options={
                'verbose_name': 'Прямая линия',
                'verbose_name_plural': 'Прямая линия',
            },
        ),
    ]
