# Generated by Django 5.0.3 on 2024-06-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_hotlinehours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotlinehours',
            name='phone_info',
        ),
    ]
