# Generated by Django 5.0.3 on 2024-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_remove_hotlinehours_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotlinehours',
            name='last_name',
        ),
        migrations.AddField(
            model_name='hotlinehours',
            name='post',
            field=models.CharField(default='Должность', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotlinehours',
            name='name',
            field=models.CharField(default='Фамилия Имя и Отчество', max_length=100),
        ),
    ]
