# Generated by Django 5.0.3 on 2024-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_remove_hotlinehours_last_name_hotlinehours_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlineHours_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Прямая Телефонная Линия', max_length=100)),
                ('description', models.CharField(default='График проведения "прямой телефонной линии" в Государственном учреждении "Полоцкий зональный центр гигиены и эпидемиологии"', max_length=300)),
            ],
            options={
                'verbose_name': 'Прямая линия тайтл и описание',
                'verbose_name_plural': 'Прямая линия тайтл и описание',
            },
        ),
        migrations.AlterField(
            model_name='hotlinehours',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
