# Generated by Django 5.0.3 on 2024-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_hotlinehours_title_alter_hotlinehours_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlineHours_Title_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Порядок проведения', max_length=100)),
                ('description', models.CharField(default='Описание проведения', max_length=300)),
            ],
            options={
                'verbose_name': 'Порядок проведения тайтл и описание',
                'verbose_name_plural': 'Порядок проведения тайтл и описание',
            },
        ),
    ]
