# Generated by Django 5.0.3 on 2024-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_hotlinehours_title_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlinehours_title_desc',
            name='description',
            field=models.CharField(default='Описание проведения', max_length=3000),
        ),
    ]
