# Generated by Django 5.0.3 on 2024-06-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_alter_hotlinehours_title_desc_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic_appeals_Title_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Порядок проведения', max_length=300)),
                ('description', models.CharField(default='Описание проведения', max_length=3000)),
            ],
            options={
                'verbose_name': 'Электронные Обращения тайтл и описание',
                'verbose_name_plural': 'Электронные Обращения тайтл и описание',
            },
        ),
        migrations.AlterField(
            model_name='hotlinehours_title_desc',
            name='name',
            field=models.CharField(default='Порядок проведения', max_length=300),
        ),
    ]
