# Generated by Django 5.0.3 on 2024-06-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_electronic_appeals_title_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ_Title_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('description', models.CharField(default='Описание', max_length=3000)),
            ],
            options={
                'verbose_name': 'Вышестоящий орган тайтл и описание',
                'verbose_name_plural': 'Вышестоящий орган тайтл и описание',
            },
        ),
    ]
