# Generated by Django 5.0.3 on 2024-06-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_up_organ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_organ',
            name='reception_time',
            field=models.CharField(default='Время Приема', max_length=200),
        ),
    ]
