# Generated by Django 5.0.3 on 2024-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_alter_up_organ_reception_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up_Organ_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Телефон горячей линии', max_length=300)),
                ('description', models.CharField(default='Время работы', max_length=3000)),
            ],
            options={
                'verbose_name': 'Информация (низ стр) Вышестоящий Орган',
                'verbose_name_plural': 'Информация (низ стр) Вышестоящий Орган',
            },
        ),
    ]
