# Generated by Django 5.0.3 on 2024-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_up_organ_inf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('description', models.CharField(default='Первое большое описание', max_length=3000)),
                ('description_two', models.CharField(default='Второе описание', max_length=3000)),
                ('description_three', models.CharField(default='Третье описание', max_length=3000)),
            ],
            options={
                'verbose_name': 'Экспертиза',
                'verbose_name_plural': 'Экспертиза',
            },
        ),
    ]
