# Generated by Django 5.0.3 on 2024-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('description', models.CharField(default='Первое большое описание', max_length=3000)),
            ],
            options={
                'verbose_name': 'Права и обязанности',
                'verbose_name_plural': 'Права и обязанности',
            },
        ),
    ]
