# Generated by Django 5.0.3 on 2024-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_duties'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('description', models.CharField(default='Большое описание', max_length=3000)),
            ],
            options={
                'verbose_name': 'Порядок и Сроки Обжалования',
                'verbose_name_plural': 'Порядок и Сроки Обжалования',
            },
        ),
        migrations.AlterField(
            model_name='duties',
            name='description',
            field=models.CharField(default='Большое описание', max_length=3000),
        ),
    ]
