# Generated by Django 5.0.3 on 2024-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_maintenanceschedule_alter_duties_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('vacancy', models.CharField(default='Вакансия 1', max_length=7000)),
                ('vacancy_two', models.CharField(default='Вакансия 2', max_length=7000)),
                ('vacancy_three', models.CharField(default='Вакансия 3', max_length=7000)),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterField(
            model_name='duties',
            name='description',
            field=models.CharField(default='Большое описание', max_length=7000),
        ),
    ]
