# Generated by Django 5.0.3 on 2024-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0057_mainappeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл Анткоррупция', max_length=100)),
                ('name_two', models.CharField(default='Тайтл2 Анткоррупция', max_length=100)),
                ('description', models.TextField(default='Featured Description')),
                ('link', models.URLField()),
                ('icon_class', models.CharField(default='fas fa-heartbeat', max_length=100)),
            ],
            options={
                'verbose_name': 'Антикоррупция',
                'verbose_name_plural': 'Антикоррупция',
            },
        ),
    ]
