# Generated by Django 5.0.3 on 2024-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_anticorr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticorr',
            name='name',
            field=models.CharField(default='Тайтл Анткоррупция', max_length=200),
        ),
        migrations.AlterField(
            model_name='anticorr',
            name='name_two',
            field=models.CharField(default='Тайтл2 Анткоррупция', max_length=200),
        ),
    ]
