# Generated by Django 5.0.3 on 2024-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0060_anticorrtitle_remove_anticorr_name_two_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('normative_desc', models.CharField(default='Описание под тайтл', max_length=300)),
            ],
            options={
                'verbose_name': 'Нормативные документы',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
    ]
