# Generated by Django 5.0.3 on 2024-06-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0061_normativedocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=100)),
                ('description', models.TextField(default='Описание')),
                ('name_two', models.CharField(default='Второе название', max_length=100)),
                ('description_two', models.TextField(default='Второе описание')),
                ('name_li_one', models.CharField(default='Первое имя с тегом li', max_length=100)),
                ('name_li_two', models.CharField(default='Второе имя с тегом li', max_length=100)),
                ('name_li_three', models.CharField(default='Третье имя с тегом li', max_length=100)),
                ('name_li_four', models.CharField(default='Четвертое имя с тегом li', max_length=100)),
                ('name_li_five', models.CharField(default='Пятое имя с тегом li', max_length=100)),
                ('description_three', models.TextField(default='Третье описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='laboratory/')),
                ('icon_class', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_one', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_two', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_three', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_four', models.CharField(default='bi bi-check-circle', max_length=100)),
                ('icon_class_li_five', models.CharField(default='bi bi-check-circle', max_length=100)),
            ],
            options={
                'verbose_name': 'Лабораторные услуги',
                'verbose_name_plural': 'Лабораторные услуги',
            },
        ),
    ]
