# Generated by Django 5.0.3 on 2024-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0062_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(default='Тайтл', max_length=150),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_li_five',
            field=models.CharField(default='Пятое имя с тегом li', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_li_four',
            field=models.CharField(default='Четвертое имя с тегом li', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_li_one',
            field=models.CharField(default='Первое имя с тегом li', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_li_three',
            field=models.CharField(default='Третье имя с тегом li', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_li_two',
            field=models.CharField(default='Второе имя с тегом li', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_two',
            field=models.CharField(default='Второе название', max_length=200),
        ),
    ]
