# Generated by Django 5.0.3 on 2024-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_alter_laboratory_name_alter_laboratory_name_li_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='icon_class_li_six',
            field=models.CharField(default='bi bi-check-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='name_li_six',
            field=models.CharField(default='Шестое имя с тегом li', max_length=200),
        ),
    ]
