# Generated by Django 5.0.3 on 2024-06-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_laboratory_icon_class_li_six_laboratory_name_li_six'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='name_three',
            field=models.CharField(default='Третье название', max_length=200),
        ),
    ]
