# Generated by Django 5.0.3 on 2024-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_laboratories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratories',
            name='name',
            field=models.CharField(default='Тайтл', max_length=150),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='name_four',
            field=models.CharField(default='Четвертое Имя', max_length=150),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='name_three',
            field=models.CharField(default='Третье Имя', max_length=150),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='name_two',
            field=models.CharField(default='Второе Имя', max_length=150),
        ),
    ]
