# Generated by Django 5.0.3 on 2024-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0067_alter_laboratories_name_alter_laboratories_name_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratories',
            name='description_icon',
            field=models.TextField(default='Первое описание'),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='description',
            field=models.TextField(default='Описание под тайтл'),
        ),
    ]
