# Generated by Django 5.0.3 on 2024-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_laboratories_description_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratories',
            name='icon_class_four',
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='icon_class_three',
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='name_four',
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='name_three',
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='name_two',
        ),
        migrations.AddField(
            model_name='laboratories',
            name='description_five',
            field=models.TextField(default='Пятое Описание'),
        ),
        migrations.AddField(
            model_name='laboratories',
            name='description_seven',
            field=models.TextField(default='Седьмое Описание'),
        ),
        migrations.AddField(
            model_name='laboratories',
            name='description_six',
            field=models.TextField(default='Шестое Описание'),
        ),
    ]
