# Generated by Django 5.0.3 on 2024-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0070_rename_description_icon_laboratories_description_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratories',
            name='name_two',
            field=models.CharField(default='Тайтл 2', max_length=150),
        ),
    ]
