# Generated by Django 5.0.3 on 2024-06-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0071_laboratories_name_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratories',
            name='name_two',
        ),
    ]
