# Generated by Django 5.0.3 on 2024-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0072_remove_laboratories_name_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratories',
            name='description_services',
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='description',
            field=models.TextField(default='Описание'),
        ),
    ]
