# Generated by Django 5.0.3 on 2024-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0073_remove_laboratories_description_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=150)),
                ('description', models.TextField(default='Описание')),
                ('description_two', models.TextField(default='Описание 2')),
                ('description_three', models.TextField(default='Описание 3')),
            ],
            options={
                'verbose_name': 'АП Регистрация',
                'verbose_name_plural': 'АП Регистрация',
            },
        ),
    ]
