# Generated by Django 5.0.3 on 2024-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0075_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=150)),
                ('description', models.TextField(default='Описание')),
                ('name_ap', models.CharField(default='Наименование административной процедуры', max_length=300)),
                ('doc_ap', models.CharField(default='Документы и (или) сведения АП', max_length=300)),
                ('size_ap', models.CharField(default='Размер Платы взымаемой при АП', max_length=300)),
            ],
            options={
                'verbose_name': 'АП Кадровая Служба',
                'verbose_name_plural': 'АП Кадровая Служба',
            },
        ),
    ]
