# Generated by Django 5.0.3 on 2024-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0076_humanresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresources',
            name='number_ap',
            field=models.CharField(default='Номер административной процедуры', max_length=300),
        ),
    ]
