# Generated by Django 5.0.3 on 2024-07-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0078_humanresourcesdesc_alter_humanresources_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=150)),
                ('number_ap', models.CharField(default='Номер административной процедуры', max_length=300)),
                ('name_ap', models.CharField(default='Наименование административной процедуры', max_length=300)),
                ('doc_ap', models.CharField(default='Документы и (или) сведения АП', max_length=300)),
                ('size_ap', models.CharField(default='Размер Платы взымаемой при АП', max_length=300)),
                ('date_ap', models.CharField(default='Сроки выполнения АП', max_length=300)),
            ],
            options={
                'verbose_name': 'АП Кадровая Служба таблица Бухгалтерия',
                'verbose_name_plural': 'АП Кадровая Служба таблица Бухгалтерия',
            },
        ),
        migrations.AddField(
            model_name='humanresources',
            name='name',
            field=models.CharField(default='Тайтл', max_length=150),
        ),
    ]
