# Generated by Django 5.0.3 on 2024-07-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0079_accounting_humanresources_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='doc_ap',
            field=models.TextField(default='Документы и (или) сведения АП'),
        ),
    ]
