# Generated by Django 5.0.3 on 2024-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0081_accountingdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='date_ap',
            field=models.CharField(default='Сроки выполнения АП', max_length=500),
        ),
    ]
