# Generated by Django 5.0.3 on 2024-07-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0082_alter_accounting_date_ap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='name_ap',
            field=models.CharField(default='Наименование административной процедуры', max_length=500),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='number_ap',
            field=models.CharField(default='Номер административной процедуры', max_length=500),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='size_ap',
            field=models.CharField(default='Размер Платы взымаемой при АП', max_length=500),
        ),
    ]
