# Generated by Django 5.0.3 on 2024-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0084_uniondesc_alter_accountingdesc_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=150)),
                ('number_ap', models.CharField(default='Номер профсоюзной процедуры', max_length=500)),
                ('name_ap', models.CharField(default='Наименование профсоюзной процедуры', max_length=500)),
                ('doc_ap', models.TextField(default='Документы и (или) сведения АП')),
                ('size_ap', models.CharField(default='Размер Платы взымаемой при АП', max_length=500)),
                ('date_ap', models.CharField(default='Сроки выполнения АП', max_length=500)),
            ],
            options={
                'verbose_name': 'АП Профсоюз таблица',
                'verbose_name_plural': 'АП Профсоюз таблица',
            },
        ),
    ]
