# Generated by Django 5.0.3 on 2024-07-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0085_union'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingDecree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Наименование АП', max_length=150)),
                ('number_ap', models.CharField(default='Номер профсоюзной процедуры', max_length=500)),
                ('name_ap', models.CharField(default='Гос орган для обращения', max_length=500)),
                ('doc_ap', models.TextField(default='Документы и (или) сведения')),
                ('size_ap', models.CharField(default='Максимальный срок', max_length=500)),
                ('date_ap', models.CharField(default='Сроки действия', max_length=500)),
            ],
            options={
                'verbose_name': 'АП указ таблица',
                'verbose_name_plural': 'АП указ таблица',
            },
        ),
        migrations.CreateModel(
            name='ListingDecreeDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=150)),
                ('description', models.TextField(default='Описание')),
            ],
            options={
                'verbose_name': 'АП Указ (в отношении граждан)',
                'verbose_name_plural': 'АП Указ (в отношении граждан)',
            },
        ),
    ]
