# Generated by Django 5.0.3 on 2024-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0087_alter_listingdecree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdecreedesc',
            name='name',
            field=models.CharField(default='Тайтл', max_length=350),
        ),
    ]
