# Generated by Django 5.0.3 on 2024-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0088_alter_listingdecreedesc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdecree',
            name='name_ap',
            field=models.CharField(default='Гос орган для обращения', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listingdecree',
            name='number_ap',
            field=models.CharField(default='Номер профсоюзной процедуры', max_length=100),
        ),
        migrations.AlterField(
            model_name='listingdecree',
            name='size_ap',
            field=models.CharField(default='Максимальный срок выполнения', max_length=500),
        ),
    ]
