# Generated by Django 5.0.3 on 2024-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0090_profsouz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfsouzDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Описание - 1')),
                ('description_two', models.TextField(default='Описание - 2')),
                ('package', models.TextField(default='Состав')),
            ],
            options={
                'verbose_name': 'О центре Профсоюз верхнее описание',
                'verbose_name_plural': 'О центре Профсоюз верхнее описание',
            },
        ),
        migrations.AlterModelOptions(
            name='profsouz',
            options={'verbose_name': 'О центре Профсоюз таблицы', 'verbose_name_plural': 'О центре Профсоюз таблицы'},
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='description_two',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='package',
        ),
    ]
