# Generated by Django 5.0.3 on 2024-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0091_profsouzdesc_alter_profsouz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profsouz',
            name='link',
        ),
        migrations.AddField(
            model_name='profsouz',
            name='link_facebook',
            field=models.URLField(default='https://facebook.com'),
        ),
        migrations.AddField(
            model_name='profsouz',
            name='link_instagram',
            field=models.URLField(default='https://instagram.com'),
        ),
        migrations.AddField(
            model_name='profsouz',
            name='link_telegram',
            field=models.URLField(default='https://telegram.com'),
        ),
        migrations.AddField(
            model_name='profsouz',
            name='link_vk',
            field=models.URLField(default='https://vk.com'),
        ),
    ]
