# Generated by Django 5.0.3 on 2024-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0092_remove_profsouz_link_profsouz_link_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profsouz',
            name='description',
            field=models.TextField(default='Описание - 1'),
        ),
        migrations.AddField(
            model_name='profsouz',
            name='description_two',
            field=models.TextField(default='Описание - 2'),
        ),
    ]
