# Generated by Django 5.0.3 on 2024-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0093_profsouz_description_profsouz_description_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfsouzDescOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Описание - 1')),
                ('description_two', models.TextField(default='Описание - 2')),
                ('package', models.TextField(default='Состав')),
            ],
            options={
                'verbose_name': 'О центре Профсоюз описание первая таблица',
                'verbose_name_plural': 'О центре Профсоюз первая таблица',
            },
        ),
    ]
