# Generated by Django 5.0.3 on 2024-07-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0094_profsouzdescone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfsouzIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('icon_telegram', models.CharField(default='bx bxl-telegram', max_length=100)),
                ('link_telegram', models.URLField(default='https://telegram.com')),
                ('icon_facebook', models.CharField(default='bx bxl-facebook', max_length=100)),
                ('link_facebook', models.URLField(default='https://facebook.com')),
                ('icon_vk', models.CharField(default='bx bxl-vkontakte', max_length=100)),
                ('link_vk', models.URLField(default='https://vk.com')),
                ('icon_instagram', models.CharField(default='bx bxl-instagram', max_length=100)),
                ('link_instagram', models.URLField(default='https://instagram.com')),
            ],
            options={
                'verbose_name': 'О центре Профсоюз Иконки',
                'verbose_name_plural': 'О центре Профсоюз Иконки',
            },
        ),
    ]
