# Generated by Django 5.0.3 on 2024-07-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0095_profsouzicons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profsouz',
            name='icon_facebook',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='icon_instagram',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='icon_telegram',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='icon_vk',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='link_telegram',
        ),
        migrations.RemoveField(
            model_name='profsouz',
            name='link_vk',
        ),
    ]
