# Generated by Django 5.0.3 on 2024-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0096_remove_profsouz_icon_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profsouzicons',
            name='description',
            field=models.TextField(default='Описание'),
        ),
    ]
