# Generated by Django 5.0.3 on 2024-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0097_profsouzicons_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profsouzicons',
            name='description_two',
            field=models.TextField(default='Описание Два'),
        ),
    ]
