# Generated by Django 5.0.3 on 2024-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0098_profsouzicons_description_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profsouzdescone',
            options={'verbose_name': 'О центре Профсоюз описание таблица', 'verbose_name_plural': 'О центре Профсоюз таблица'},
        ),
        migrations.AddField(
            model_name='profsouzdescone',
            name='name_main',
            field=models.CharField(default='Тайтл на страницу', max_length=350),
        ),
    ]
