# Generated by Django 5.0.3 on 2024-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0099_alter_profsouzdescone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfsouzTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Описание - 1')),
                ('description_two', models.TextField(default='Описание - 2')),
                ('number', models.CharField(default='Номер строки(ячейки в таблице)', max_length=350)),
                ('name_doctors', models.TextField(default='ФИО Доктор')),
                ('status', models.TextField(default='Должность')),
                ('phone', models.TextField(default='Телефон')),
            ],
            options={
                'verbose_name': 'О центре Профсоюз таблицы с сотрудниками (таблица 2)',
                'verbose_name_plural': 'О центре Профсоюз таблицы с сотрудниками (таблица 2)',
            },
        ),
        migrations.AlterModelOptions(
            name='profsouz',
            options={'verbose_name': 'О центре Профсоюз таблицы с сотрудниками', 'verbose_name_plural': 'О центре Профсоюз таблицы с сотрудниками'},
        ),
        migrations.AlterModelOptions(
            name='profsouzdescone',
            options={'verbose_name': 'О центре Профсоюз описание таблицы', 'verbose_name_plural': 'О центре Профсоюз таблицы'},
        ),
    ]
