# Generated by Django 5.0.3 on 2024-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0101_disinfection'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinfection',
            name='description_two',
            field=models.TextField(default='Описание 2'),
        ),
    ]
