# Generated by Django 5.0.3 on 2024-07-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0105_disinfectiondesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл для админки', max_length=350)),
                ('name_main', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Описание')),
            ],
            options={
                'verbose_name': 'АП перечень',
                'verbose_name_plural': 'АП перечень',
            },
        ),
    ]
