# Generated by Django 5.0.3 on 2024-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0107_inventory_description_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNadzor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Заголовок таблицы - 1')),
                ('description_two', models.TextField(default='Заголовок таблицы - 2')),
                ('description_three', models.TextField(default='Заголовок таблицы - 3')),
                ('number', models.CharField(default='Номер строки(ячейки в таблице)', max_length=350)),
                ('objects_control', models.TextField(default='Объекты контроля')),
                ('typical_violations', models.TextField(default='Типичные нарушения')),
                ('name_typical_violations', models.TextField(default='Наименования технических регламентов')),
            ],
            options={
                'verbose_name': 'Контрольно надзорная деятельность(таблица)',
                'verbose_name_plural': 'Контрольно надзорная деятельность(таблица)',
            },
        ),
    ]
