# Generated by Django 5.0.3 on 2024-07-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0108_controlnadzor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControlNadzor',
            new_name='ControlNadzorTipical',
        ),
    ]
