# Generated by Django 5.0.3 on 2024-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0111_controlnadzortipical_name_typical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNadTipicalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл для админки', max_length=350)),
                ('name_typical', models.CharField(default='Тайтл', max_length=350)),
            ],
            options={
                'verbose_name': 'Контрольно надзорная деятельность Типичные нарушения (Тайтл)',
                'verbose_name_plural': 'Контрольно надзорная деятельность Типичные нарушения(Тайтл)',
            },
        ),
    ]
