# Generated by Django 5.0.3 on 2024-07-23 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0112_cnadtipicalname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductsInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл (для админ)', max_length=350)),
                ('name_typical', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Заголовок таблицы - 1')),
                ('description_two', models.TextField(default='Заголовок таблицы - 2')),
                ('description_three', models.TextField(default='Заголовок таблицы - 3')),
                ('number', models.CharField(default='Номер строки(ячейки в таблице)', max_length=350)),
                ('objects_control', models.TextField(default='Объекты контроля')),
                ('typical_violations', models.TextField(default='Типичные нарушения')),
                ('name_typical_violations', models.TextField(default='Наименования технических регламентов')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации')),
            ],
            options={
                'verbose_name': 'Контрольно надзорная деятельность Нестандартная продукция (таблица)',
                'verbose_name_plural': 'Контрольно надзорная деятельность Нестандартная продукция(таблица)',
            },
        ),
        migrations.CreateModel(
            name='CustomProductsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл для админки', max_length=350)),
                ('name_typical', models.CharField(default='Тайтл', max_length=350)),
            ],
            options={
                'verbose_name': 'Контрольно надзорная деятельность Нестандартная продукция (Тайтл)',
                'verbose_name_plural': 'Контрольно надзорная деятельность Нестандартная продукция(Тайтл)',
            },
        ),
    ]
