# Generated by Django 5.0.3 on 2024-07-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0113_customproductsinf_customproductsname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproductsinf',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='customproductsinf',
            name='description_two',
        ),
        migrations.RemoveField(
            model_name='customproductsinf',
            name='name_typical_violations',
        ),
        migrations.RemoveField(
            model_name='customproductsinf',
            name='number',
        ),
        migrations.RemoveField(
            model_name='customproductsinf',
            name='objects_control',
        ),
        migrations.RemoveField(
            model_name='customproductsinf',
            name='typical_violations',
        ),
        migrations.AlterField(
            model_name='customproductsinf',
            name='description',
            field=models.TextField(default='Описание'),
        ),
    ]
