# Generated by Django 5.0.3 on 2024-07-25 14:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0114_remove_customproductsinf_description_three_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAnalytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('pdf_file', models.FileField(upload_to='pdfs/', verbose_name='Прикрепить PDF')),
                ('icon_class', models.CharField(default='fas fa-file-pdf', max_length=100)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата Публикации')),
            ],
            options={
                'verbose_name': 'Информационно-аналитический бюллетень',
                'verbose_name_plural': 'Информационно-аналитический бюллетень',
                'ordering': ['-pub_date'],
            },
        ),
    ]
