# Generated by Django 5.0.3 on 2024-07-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0115_informationanalytical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationanalytical',
            name='description',
        ),
    ]
