# Generated by Django 5.0.3 on 2024-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0116_remove_informationanalytical_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconimicSouz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=300)),
                ('normative_desc', models.CharField(default='Описание под тайтл', max_length=300)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
            options={
                'verbose_name': 'Еврозийский экономичекский союз',
                'verbose_name_plural': 'Еврозийский экономичекский союз',
            },
        ),
    ]
