# Generated by Django 5.0.3 on 2024-07-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0117_econimicsouz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econimicsouz',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
