# Generated by Django 5.0.3 on 2024-07-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0118_alter_econimicsouz_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='econimicsouz',
            old_name='normative_desc',
            new_name='desc',
        ),
    ]
