# Generated by Django 5.0.3 on 2024-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0119_rename_normative_desc_econimicsouz_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='econimicsouz',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
