# Generated by Django 5.0.3 on 2024-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0120_econimicsouz_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='econimicsouz',
            name='name_main',
            field=models.CharField(blank=True, default='Тайтл заглавный', max_length=300),
        ),
        migrations.AlterField(
            model_name='econimicsouz',
            name='desc',
            field=models.CharField(default='Описание под тайтл', max_length=1000),
        ),
        migrations.AlterField(
            model_name='econimicsouz',
            name='name',
            field=models.CharField(default='Тайтл', max_length=500),
        ),
    ]
