# Generated by Django 5.0.3 on 2024-07-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0121_econimicsouz_name_main_alter_econimicsouz_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econimicsouz',
            name='name_main',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
