# Generated by Django 5.0.3 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0122_alter_econimicsouz_name_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econimicsouz',
            name='name_main',
            field=models.CharField(blank=True, default='Тайтл заглавный', max_length=300),
        ),
    ]
