# Generated by Django 5.0.3 on 2024-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0123_alter_econimicsouz_name_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='econimicsouz',
            name='icon_class',
            field=models.CharField(default='fas fa-heartbeat', max_length=100),
        ),
    ]
