# Generated by Django 5.0.3 on 2024-07-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0124_econimicsouz_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('description', models.TextField(default='Описание')),
                ('pdf_file', models.FileField(upload_to='pdfs/', verbose_name='Прикрепить PDF')),
                ('pdf_file_two', models.FileField(upload_to='pdfs/', verbose_name='Прикрепить PDF 2')),
                ('icon_class', models.CharField(default='fas fa-file-pdf', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Objectives/')),
            ],
            options={
                'verbose_name': 'Цели устойчивого развития',
                'verbose_name_plural': 'Цели устойчивого развития',
            },
        ),
    ]
