# Generated by Django 5.0.3 on 2024-07-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0127_remove_objectives_description_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectives',
            name='photo',
        ),
    ]
