# Generated by Django 5.0.3 on 2024-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0128_remove_objectives_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('description', models.TextField(default='Описание')),
                ('description_two', models.TextField(default='Описание 2')),
                ('google_map_embed_code', models.TextField(blank=True, null=True, verbose_name='Код вставки Google Карт')),
            ],
            options={
                'verbose_name': 'Внимание клещи',
                'verbose_name_plural': 'Внимание клещи',
            },
        ),
    ]
