# Generated by Django 5.0.3 on 2024-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0129_ticks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticks',
            name='name_map',
            field=models.CharField(default='Имя для карт', max_length=300),
        ),
    ]
