# Generated by Django 5.0.3 on 2024-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0130_ticks_name_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticks',
            name='name_map',
            field=models.CharField(default='Имя для карт', max_length=700),
        ),
    ]
