# Generated by Django 5.0.3 on 2024-08-01 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0133_remove_epidemialogyinf_name_typical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemialogyTipical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Описание')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации')),
            ],
            options={
                'verbose_name': 'Эпидемиалогия (статьи)',
                'verbose_name_plural': 'Эпидемиалогия (статьи)',
            },
        ),
    ]
