# Generated by Django 5.0.3 on 2024-08-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0134_epidemialogytipical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epidemialogyinf',
            options={'verbose_name': 'Эпидемиалогия (название и краткое описание статьи)', 'verbose_name_plural': 'Эпидемиалогия (название и краткое описание статьи)'},
        ),
        migrations.AlterModelOptions(
            name='epidemialogysinglename',
            options={'verbose_name': 'Эпидемиалогия (Тайтл страницы статьи)', 'verbose_name_plural': 'Эпидемиалогия (Тайтл страницы статьи)'},
        ),
    ]
