# Generated by Django 5.0.3 on 2024-08-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0135_alter_epidemialogyinf_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpidemialogySingleName',
        ),
    ]
