# Generated by Django 5.0.3 on 2024-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0136_delete_epidemialogysinglename'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemialogytipical',
            name='description_three',
            field=models.TextField(default='Третье описание'),
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='description_two',
            field=models.TextField(default='Второе описание'),
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='name_three',
            field=models.CharField(default='Третье название', max_length=200),
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='name_two',
            field=models.CharField(default='Второе название', max_length=200),
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Epidemialogy/'),
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='photo_bg',
            field=models.ImageField(blank=True, null=True, upload_to='Epidemialogy/'),
        ),
    ]
