# Generated by Django 5.0.3 on 2024-08-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0137_epidemialogytipical_description_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epidemialogytipical',
            old_name='photo_bg',
            new_name='photo_two',
        ),
    ]
