# Generated by Django 5.0.3 on 2024-08-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0139_immunoprophylaxisinf_immunoprophylaxisname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunoprophylaxistipical',
            name='photo_two',
        ),
    ]
