# Generated by Django 5.0.3 on 2024-08-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0140_remove_immunoprophylaxistipical_photo_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_main', models.CharField(blank=True, default='Тайтл заглавный', max_length=300)),
                ('name', models.CharField(default='Тайтл', max_length=500)),
                ('desc', models.CharField(default='Описание под тайтл', max_length=1000)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdfs/')),
                ('link', models.URLField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-heartbeat', max_length=100)),
            ],
            options={
                'verbose_name': 'Санитарно - Карантинные пункты',
                'verbose_name_plural': 'Санитарно - Карантинные пункты',
            },
        ),
    ]
