# Generated by Django 5.0.3 on 2024-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0141_quarantine'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine',
            name='desc_two',
            field=models.CharField(default='СКП', max_length=1000),
        ),
    ]
