# Generated by Django 5.0.3 on 2024-08-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0142_quarantine_desc_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemSituations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Тайтл заглавный', max_length=300)),
                ('desc', models.CharField(default='Описание под тайтл', max_length=1000)),
            ],
            options={
                'verbose_name': 'Санитарно - Карантинные пункты',
                'verbose_name_plural': 'Санитарно - Карантинные пункты',
            },
        ),
    ]
