# Generated by Django 5.0.3 on 2024-08-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0143_epidemsituations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epidemsituations',
            options={'verbose_name': 'Эпидемиологическая Ситуация', 'verbose_name_plural': 'Эпидемиологическая Ситуация'},
        ),
    ]
