# Generated by Django 5.0.3 on 2024-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0144_alter_epidemsituations_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemsituations',
            name='desc',
            field=models.TextField(default='Описание под тайтл'),
        ),
        migrations.AlterField(
            model_name='epidemsituations',
            name='name',
            field=models.CharField(blank=True, default='Тайтл заглавный', max_length=1000),
        ),
    ]
