# Generated by Django 5.0.3 on 2024-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0145_alter_epidemsituations_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine',
            name='desc_two',
            field=models.CharField(blank=True, default='СКП', max_length=1000),
        ),
    ]
