# Generated by Django 5.0.3 on 2024-08-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0147_alter_quarantine_desc_alter_quarantine_desc_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Тайтл заглавный', max_length=1000)),
                ('desc', models.TextField(default='Описание под тайтл')),
            ],
            options={
                'verbose_name': 'Перечень стран неблагополучных по заболеваниям',
                'verbose_name_plural': 'Перечень стран неблагополучных по заболеваниям',
            },
        ),
    ]
