# Generated by Django 5.0.3 on 2024-08-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0148_countryregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Тайтл заглавный', max_length=1000)),
                ('desc', models.TextField(default='Описание под тайтл')),
            ],
            options={
                'verbose_name': 'Постановление Минздрава (стр карантин)',
                'verbose_name_plural': 'Постановление Минздрава (стр карантин)',
            },
        ),
    ]
