# Generated by Django 5.0.3 on 2024-08-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0150_healthy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthy',
            name='name_taitle',
            field=models.CharField(max_length=100, verbose_name='Имя для Заголовка'),
        ),
    ]
