# Generated by Django 5.0.3 on 2024-08-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0152_healthytitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthy',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='healthy',
            name='name_taitle',
            field=models.CharField(max_length=100, verbose_name='Описание под тайтл'),
        ),
    ]
