# Generated by Django 5.0.3 on 2024-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0153_alter_healthy_name_alter_healthy_name_taitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemialogytipical',
            name='description_small',
            field=models.TextField(default='Описание для стр Эпидемиалогия'),
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='name_main',
            field=models.CharField(default='Тайтл для страницы Эпидемиалогия', max_length=350),
        ),
    ]
