# Generated by Django 5.0.3 on 2024-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0155_remove_epidemialogytipical_name_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemialogytipical',
            name='name_epidem',
            field=models.CharField(default='Тайтл ля стр. Эпидемиалогия', max_length=350),
        ),
        migrations.AlterField(
            model_name='epidemialogytipical',
            name='description_small',
            field=models.TextField(default='Описание для стр. Эпидемиалогия'),
        ),
    ]
