# Generated by Django 5.0.3 on 2024-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0156_epidemialogytipical_name_epidem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoHad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='имя для админки', max_length=50)),
                ('working_days', models.CharField(default='Пн - Пт, 8.00 - 17.00', max_length=50)),
                ('lunch_time', models.CharField(default='Обед: 13.00 - 14.00', max_length=50)),
                ('phone_number', models.CharField(default='+80214493168', max_length=20)),
                ('email_address', models.EmailField(default='polotzk_hyg@vitebsk.by', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='epidemialogytipical',
            name='name_epidem',
            field=models.CharField(default='Тайтл ля стр. Эпидемиалогия (h3)', max_length=350),
        ),
    ]
