# Generated by Django 5.0.3 on 2024-08-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0157_contactinfohad_alter_epidemialogytipical_name_epidem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfohad',
            options={'verbose_name': 'Контактная информация для Had', 'verbose_name_plural': 'Контактная информация для Had'},
        ),
    ]
