# Generated by Django 5.0.3 on 2024-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0160_alter_contactinfohad_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfohad',
            name='email_address',
            field=models.CharField(default='Наша почта: polotzk_hyg@vitebsk.by', max_length=70),
        ),
        migrations.AlterField(
            model_name='contactinfohad',
            name='phone_number',
            field=models.CharField(default='Наш телефон: +80214493168', max_length=25),
        ),
    ]
