# Generated by Django 5.0.3 on 2024-08-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0161_alter_contactinfohad_email_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfohad',
            options={'verbose_name': 'Контактная информация для Top Bar', 'verbose_name_plural': 'Контактная информация для Top Bar'},
        ),
    ]
