# Generated by Django 5.0.3 on 2024-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0162_alter_contactinfohad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfohad',
            name='phone_number',
            field=models.CharField(default='Наш телефон: +80214493168', max_length=50),
        ),
    ]
