# Generated by Django 5.0.3 on 2024-08-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0163_alter_contactinfohad_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(default='Описание', max_length=100)),
                ('indicators', models.CharField(default='Показатели', max_length=100)),
                ('catering_workers', models.CharField(default='Работники торговли и общепита', max_length=100)),
                ('after_workers', models.CharField(default='Работники водоснабжения', max_length=100)),
                ('employees_school', models.CharField(default='Работники водоснабжения', max_length=100)),
            ],
            options={
                'verbose_name': 'О проведении обязательных и внеочередных медицинских осмотров работающих',
                'verbose_name_plural': 'О проведении обязательных и внеочередных медицинских осмотров работающих',
            },
        ),
    ]
