# Generated by Django 5.0.3 on 2024-08-30 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0164_studies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesLawyerInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('description', models.TextField(default='Описание')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации')),
            ],
            options={
                'verbose_name': 'Пл услуги Юр лицам и ИП (название и краткое описание статьи)',
                'verbose_name_plural': 'Пл услуги Юр лицам и ИП (название и краткое описание статьи)',
            },
        ),
        migrations.CreateModel(
            name='ServicesLawyerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
            ],
            options={
                'verbose_name': 'Пл услуги Юр лицам и ИП (Тайтл)',
                'verbose_name_plural': 'Пл услуги Юр лицам и ИП (Тайтл)',
            },
        ),
    ]
