# Generated by Django 5.0.3 on 2024-08-30 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0165_serviceslawyerinf_serviceslawyername'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesLawyerTipical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_small', models.TextField(default='Описание для стр. Юр лиц и ИП')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('name_lawyer', models.CharField(default='Тайтл ля стр. Юр лиц и ИП (h3)', max_length=350)),
                ('name_two', models.CharField(default='Второе название', max_length=200)),
                ('name_three', models.CharField(default='Третье название', max_length=200)),
                ('description', models.TextField(default='Описание')),
                ('description_two', models.TextField(default='Второе описание')),
                ('description_three', models.TextField(default='Третье описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Lawyer/')),
                ('photo_two', models.ImageField(blank=True, null=True, upload_to='Lawyer/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации')),
            ],
            options={
                'verbose_name': 'Пл услуги Юр лицам и ИП (статьи)',
                'verbose_name_plural': 'Пл услуги Юр лицам и ИП (статьи)',
            },
        ),
    ]
