# Generated by Django 5.0.3 on 2024-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0166_serviceslawyertipical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpidemialogyInf',
        ),
        migrations.DeleteModel(
            name='ServicesLawyerInf',
        ),
        migrations.AlterField(
            model_name='epidemialogytipical',
            name='name',
            field=models.CharField(default='Тайтл для админки', max_length=350),
        ),
        migrations.AlterField(
            model_name='serviceslawyertipical',
            name='name',
            field=models.CharField(default='Тайтл для админки', max_length=350),
        ),
    ]
