# Generated by Django 5.0.3 on 2024-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0167_delete_epidemialogyinf_delete_serviceslawyerinf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
