# Generated by Django 5.0.3 on 2024-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0168_alter_studies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='desc',
            field=models.CharField(default='Описание', max_length=500),
        ),
    ]
