# Generated by Django 5.0.3 on 2024-08-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0170_alter_studies_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='after_workers',
            field=models.CharField(blank=True, default='Работники водоснабжения', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='catering_workers',
            field=models.CharField(blank=True, default='Работники торговли и общепита', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studies',
            name='employees_school',
            field=models.CharField(blank=True, default='Работники школ', max_length=100, null=True),
        ),
    ]
