# Generated by Django 5.0.3 on 2024-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0171_alter_studies_after_workers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualitySafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desc', models.CharField(default='Описание', max_length=500)),
                ('indicators', models.TextField(default='Показатели')),
                ('mine_well', models.CharField(blank=True, default='Шахтный колодец', max_length=100, null=True)),
                ('basic', models.CharField(blank=True, default='Базовый', max_length=100, null=True)),
                ('standart', models.CharField(blank=True, default='Стандарт', max_length=100, null=True)),
                ('standart_plus', models.CharField(blank=True, default='Стандарт Плюс', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'О проведении обязательных и внеочередных медицинских осмотров работающих',
                'verbose_name_plural': 'О проведении обязательных и внеочередных медицинских осмотров работающих',
            },
        ),
    ]
