# Generated by Django 5.0.3 on 2024-08-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0172_waterqualitysafety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterqualitysafety',
            options={'verbose_name': 'Лабораторные исследования воды на качество и безопасность', 'verbose_name_plural': 'Лабораторные исследования воды на качество и безопасность'},
        ),
    ]
