# Generated by Django 5.0.3 on 2024-08-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0175_laboratoryfruitvegetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EripPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_two', models.TextField(verbose_name='Описание два')),
                ('payment_methods', models.TextField(verbose_name='Методы оплаты')),
                ('payment_scheme_image1', models.ImageField(upload_to='payment_schemes/', verbose_name='Схема проведения платежа 1')),
                ('payment_scheme_image2', models.ImageField(upload_to='payment_schemes/', verbose_name='Схема проведения платежа 2')),
            ],
        ),
    ]
