# Generated by Django 5.0.3 on 2024-08-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0176_erippayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erippayment',
            name='payment_scheme_image2',
        ),
        migrations.AddField(
            model_name='erippayment',
            name='payment_scheme_image3',
            field=models.ImageField(blank=True, upload_to='payment_schemes/', verbose_name='Мальчик'),
        ),
        migrations.AddField(
            model_name='erippayment',
            name='payment_scheme_image4',
            field=models.ImageField(blank=True, upload_to='payment_schemes/', verbose_name='Книжка'),
        ),
        migrations.AddField(
            model_name='erippayment',
            name='payment_scheme_image5',
            field=models.ImageField(blank=True, upload_to='payment_schemes/', verbose_name='Стрелка'),
        ),
        migrations.AddField(
            model_name='erippayment',
            name='payment_scheme_image6',
            field=models.ImageField(blank=True, upload_to='payment_schemes/', verbose_name='токен поратл'),
        ),
        migrations.AddField(
            model_name='erippayment',
            name='title_portal',
            field=models.TextField(blank=True, verbose_name='ПОРТАЛ РЕЙТИНГОВОЙ ОЦЕНКИ'),
        ),
        migrations.AddField(
            model_name='erippayment',
            name='unp',
            field=models.TextField(blank=True, verbose_name='УНП'),
        ),
        migrations.AlterField(
            model_name='erippayment',
            name='payment_methods',
            field=models.TextField(verbose_name='Схема проведения платежа'),
        ),
    ]
