# Generated by Django 5.0.3 on 2024-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0177_remove_erippayment_payment_scheme_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos_day/', verbose_name='для фото дня')),
            ],
            options={
                'verbose_name': 'Фото дня',
                'verbose_name_plural': 'Фото дня',
            },
        ),
        migrations.AlterModelOptions(
            name='erippayment',
            options={'verbose_name': 'ЕРИП данные', 'verbose_name_plural': 'ЕРИП данные'},
        ),
    ]
