# Generated by Django 5.0.3 on 2024-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0178_photoday_alter_erippayment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('adres', models.TextField(verbose_name='Адрес')),
                ('mail', models.TextField(verbose_name='Почта')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакты данные',
                'verbose_name_plural': 'Контакты данные',
            },
        ),
    ]
