# Generated by Django 5.0.3 on 2024-09-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0179_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ИМЯ')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата Публикации')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('desc_hover', models.TextField(verbose_name='Описание при наведении')),
                ('img', models.ImageField(upload_to='CentreNews/', verbose_name='photo')),
                ('author', models.TextField(verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блок с новостями(зелено-красный)',
                'verbose_name_plural': 'Блок с новостями(зелено-красный)',
            },
        ),
    ]
