# Generated by Django 5.0.3 on 2024-09-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0180_centrenews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceslawyertipical',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='serviceslawyertipical',
            name='name_three',
        ),
        migrations.RemoveField(
            model_name='serviceslawyertipical',
            name='name_two',
        ),
    ]
