# Generated by Django 5.0.3 on 2024-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0181_remove_serviceslawyertipical_description_three_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epidemialogytipical',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='epidemialogytipical',
            name='description_two',
        ),
        migrations.RemoveField(
            model_name='epidemialogytipical',
            name='name_three',
        ),
        migrations.RemoveField(
            model_name='epidemialogytipical',
            name='name_two',
        ),
        migrations.AddField(
            model_name='epidemialogytipical',
            name='description2',
            field=models.TextField(default='Второе описание'),
        ),
    ]
