# Generated by Django 5.0.3 on 2024-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0182_remove_epidemialogytipical_description_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductsinf',
            name='description_small',
            field=models.TextField(default='Описание для гл.стр. Не стандартная Продукция'),
        ),
    ]
