# Generated by Django 5.0.3 on 2024-09-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0183_customproductsinf_description_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproductsinf',
            name='description_small',
            field=models.TextField(default='Не большое описание для гл.стр. Не стандартная Продукция'),
        ),
    ]
