# Generated by Django 5.0.3 on 2024-09-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0184_alter_customproductsinf_description_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='up_file_fiz',
            field=models.FileField(default='Добавить файл для физ', upload_to=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='up_file_your',
            field=models.FileField(default='Добавить файл для юр', upload_to=''),
        ),
    ]
