# Generated by Django 5.0.3 on 2024-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0185_inventory_up_file_fiz_inventory_up_file_your'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='up_file_fiz',
            field=models.FileField(default='Добавить файл для физ', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='up_file_your',
            field=models.FileField(default='Добавить файл для юр', upload_to='files/'),
        ),
    ]
