# Generated by Django 5.0.3 on 2024-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0186_alter_inventory_up_file_fiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='blanks',
            field=models.TextField(default='Бланки для файлов'),
        ),
    ]
