# Generated by Django 5.0.3 on 2024-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0188_remove_inventory_blanks_inventory_blank_lawyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlanksInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл для админки', max_length=350)),
                ('name_for_blanks', models.CharField(default='Тайтл для бланков', max_length=350)),
                ('blank_lawyer', models.TextField(default='Бланк для Юр лица')),
                ('blanks_civilnyi', models.TextField(default='Бланк для Физ лица')),
                ('up_file_fiz', models.FileField(default='Добавить файл для физ', upload_to='files/')),
                ('up_file_your', models.FileField(default='Добавить файл для юр', upload_to='files/')),
            ],
            options={
                'verbose_name': 'АП Бланки (перечень)',
                'verbose_name_plural': 'АП Бланки (перечень)',
            },
        ),
    ]
