# Generated by Django 5.0.3 on 2024-09-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0189_blanksinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='blank_lawyer',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='blanks_civilnyi',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name_for_blanks',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='up_file_fiz',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='up_file_your',
        ),
    ]
