# Generated by Django 5.0.3 on 2024-09-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0190_remove_inventory_blank_lawyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blanksinventory',
            name='blank_lawyer',
        ),
        migrations.RemoveField(
            model_name='blanksinventory',
            name='blanks_civilnyi',
        ),
        migrations.RemoveField(
            model_name='blanksinventory',
            name='up_file_fiz',
        ),
        migrations.RemoveField(
            model_name='blanksinventory',
            name='up_file_your',
        ),
        migrations.AddField(
            model_name='blanksinventory',
            name='blanks_all',
            field=models.TextField(default='Бланк для Имени например (Бланк для Юр лица)'),
        ),
        migrations.AddField(
            model_name='blanksinventory',
            name='up_file',
            field=models.FileField(default='Добавить файл', upload_to='files/'),
        ),
    ]
