# Generated by Django 5.0.3 on 2024-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0191_remove_blanksinventory_blank_lawyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanksinventory',
            name='name_for_blanks',
            field=models.CharField(default='Тайтл для бланков(отображается один, первый)', max_length=350),
        ),
    ]
