# Generated by Django 5.0.3 on 2024-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0192_alter_blanksinventory_name_for_blanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя Слайдер партнеры')),
                ('img', models.ImageField(upload_to='Slider-Partners/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Слайдер Партнеры',
                'verbose_name_plural': 'Слайдер Партнеры',
            },
        ),
    ]
