# Generated by Django 5.0.3 on 2024-09-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0193_ourpartners'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartners',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
