# Generated by Django 5.0.3 on 2024-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0195_pricelists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelists',
            name='icon_class',
            field=models.CharField(default='fas fa-file-invoice', max_length=100),
        ),
    ]
