# Generated by Django 5.0.3 on 2024-09-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0196_alter_pricelists_icon_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImmunoprophylaxisName',
        ),
    ]
