# Generated by Django 5.0.3 on 2024-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0197_delete_immunoprophylaxisname'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunoprophylaxisinf',
            name='name_page',
            field=models.CharField(default='Тайтл для страницы имунопрофилактика', max_length=350),
        ),
    ]
