# Generated by Django 5.0.3 on 2024-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0199_pricelistsfiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл', max_length=350)),
                ('name_main', models.CharField(default='Тайтл для Города', max_length=350)),
                ('description', models.TextField(default='Описание')),
                ('description_two', models.TextField(default='Описание при клике')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Health_cities/')),
            ],
            options={
                'verbose_name': 'Здоровые города и поселки Инф для блока',
                'verbose_name_plural': 'Здоровые города и поселки Инф для блока',
            },
        ),
    ]
