# Generated by Django 5.0.3 on 2024-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0200_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='description_three',
            field=models.TextField(default='Развернутое Описание'),
        ),
    ]
