# Generated by Django 5.0.3 on 2024-09-09 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0201_cities_description_three'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='description_two',
        ),
        migrations.CreateModel(
            name='CityDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_two', models.TextField(default='Описание при клике')),
                ('description_three', models.TextField(default='Развернутое Описание')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='webapp.cities')),
            ],
            options={
                'verbose_name': 'Описание города',
                'verbose_name_plural': 'Описания городов',
            },
        ),
    ]
