# Generated by Django 5.0.3 on 2024-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0203_alter_citydescription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тайтл для блока города', max_length=350)),
            ],
            options={
                'verbose_name': 'Здоровые города и поселки (Тайтл для блока города)',
                'verbose_name_plural': 'Здоровые города и поселки (Тайтл для блока города)',
            },
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Здоровые города и поселки (Тайтл описание фото)', 'verbose_name_plural': 'Здоровые города и поселки (Тайтл описание фото)'},
        ),
        migrations.AlterModelOptions(
            name='citydescription',
            options={'verbose_name': 'Здоровые города и поселки - Главное Описание города при нажатии', 'verbose_name_plural': 'Здоровые города и поселки - Главное Описания городов при нажатии'},
        ),
        migrations.RemoveField(
            model_name='cities',
            name='name_main',
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(default='Тайтл для Посёлка', max_length=350),
        ),
    ]
