# Generated by Django 5.0.3 on 2024-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0204_citiestitle_alter_cities_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citiestitle',
            options={'verbose_name': 'Здоровые города и поселки (Тайтл для блока Посёлка)', 'verbose_name_plural': 'Здоровые города и поселки (Тайтл для блока Посёлка)'},
        ),
        migrations.AlterModelOptions(
            name='healthy',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Здоровые города и поселки (ФАЙЛЫ)', 'verbose_name_plural': 'Здоровые города и поселки (ФАЙЛЫ)'},
        ),
        migrations.AlterModelOptions(
            name='healthytitle',
            options={'verbose_name': 'Здоровые города и поселки (Верхний ТАЙТЛ и ОПИСАНИЕ)', 'verbose_name_plural': 'Здоровые города и поселки (Верхний ТАЙТЛ и ОПИСАНИЕ)'},
        ),
        migrations.AddField(
            model_name='citydescription',
            name='add_file',
            field=models.FileField(blank=True, upload_to='pdfs/', verbose_name='Прикрепить PDF'),
        ),
    ]
