# Generated by Django 5.0.3 on 2024-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0205_alter_citiestitle_options_alter_healthy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('description', models.TextField(default='Description')),
                ('link', models.URLField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-file-invoice', max_length=100)),
                ('add_file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Нормативные документы',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
    ]
