# Generated by Django 5.0.3 on 2024-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0206_normativedoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normativedoc',
            options={'verbose_name': 'Нормативные документы (описание и файлы)', 'verbose_name_plural': 'Нормативные документы (описание и файлы)'},
        ),
        migrations.AlterField(
            model_name='normativedoc',
            name='add_file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
