# Generated by Django 5.0.3 on 2024-10-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0207_alter_normativedoc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'История - Описание',
                'verbose_name_plural': 'История - Описание',
            },
        ),
    ]
