# Generated by Django 5.0.3 on 2024-10-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0208_abouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
