# Generated by Django 5.0.3 on 2024-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0213_citydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydocument',
            name='file_desc',
            field=models.TextField(default='Description file'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='citydocument',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
