# Generated by Django 5.0.3 on 2024-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0214_citydocument_file_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDocumenFarinovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description')),
                ('file_desc', models.TextField(default='Description file')),
                ('pdf_file', models.FileField(upload_to='city_documents/')),
            ],
            options={
                'verbose_name': 'Поселок - Фариново (страница прикрепить ПДФ, архив)',
                'verbose_name_plural': 'Поселок - Фариново (страница прикрепить ПДФ, архив)',
            },
        ),
        migrations.RenameModel(
            old_name='CityDocument',
            new_name='CityDocumenBtogatyr',
        ),
        migrations.AlterModelOptions(
            name='citydocumenbtogatyr',
            options={'verbose_name': 'Поселок - Богатырский (страница прикрепить ПДФ, архив)', 'verbose_name_plural': 'Поселок - Богатырский (страница прикрепить ПДФ, архив)'},
        ),
    ]
