# Generated by Django 5.0.3 on 2024-10-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0215_citydocumenfarinovo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='url',
            new_name='rl',
        ),
        migrations.RemoveField(
            model_name='erippayment',
            name='description_two',
        ),
    ]
