# Generated by Django 5.0.3 on 2024-10-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0216_rename_url_cities_rl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='rl',
            new_name='url',
        ),
    ]
