# Generated by Django 5.0.3 on 2024-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0217_rename_rl_cities_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDocumenVetrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description')),
                ('file_desc', models.TextField(default='Description file')),
                ('pdf_file', models.FileField(upload_to='city_documents/')),
            ],
            options={
                'verbose_name': 'Поселок - Ветрино (страница прикрепить ПДФ, архив)',
                'verbose_name_plural': 'Поселок - Ветрино (страница прикрепить ПДФ, архив)',
            },
        ),
        migrations.CreateModel(
            name='CityDocumenZaozerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description')),
                ('file_desc', models.TextField(default='Description file')),
                ('pdf_file', models.FileField(upload_to='city_documents/')),
            ],
            options={
                'verbose_name': 'Поселок - Заозерье (страница прикрепить ПДФ, архив)',
                'verbose_name_plural': 'Поселок - Заозерье (страница прикрепить ПДФ, архив)',
            },
        ),
    ]
