# Generated by Django 5.0.3 on 2024-10-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0218_citydocumenvetrino_citydocumenzaozerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='file_desc',
            field=models.TextField(default='Description file'),
        ),
        migrations.AddField(
            model_name='cities',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='city_documents/'),
        ),
    ]
