# Generated by Django 5.0.3 on 2024-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0220_cities_description_two_alter_cities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='name_city',
            field=models.CharField(default='Тайтл для Посёлка на странице посёлка', max_length=350),
        ),
    ]
