# Generated by Django 5.0.3 on 2024-10-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0221_cities_name_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityDocumenBtogatyr',
        ),
        migrations.DeleteModel(
            name='CityDocumenFarinovo',
        ),
        migrations.DeleteModel(
            name='CityDocumenVetrino',
        ),
        migrations.DeleteModel(
            name='CityDocumenZaozerie',
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Здоровые города и поселки (Тайтл описание фото, добавить посёлок)', 'verbose_name_plural': 'Здоровые города и поселки (Тайтл описание фото, добавить посёлок)'},
        ),
    ]
