# Generated by Django 5.0.3 on 2024-10-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0222_delete_citydocumenbtogatyr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydescription',
            options={'verbose_name': 'Здоровые города и поселки - Интерактивная Доска', 'verbose_name_plural': 'Здоровые города и поселки - Интерактивная Доска'},
        ),
    ]
