# Generated by Django 5.0.3 on 2024-11-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0224_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratories',
            name='description_two',
            field=models.TextField(default='Второе (нижнее) Описание'),
        ),
    ]
