# Generated by Django 5.0.3 on 2024-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0226_remove_laboratories_description_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('payment_where', models.TextField(verbose_name='Где сделать платёж')),
                ('payment_methods', models.TextField(verbose_name='Схема проведения платежа')),
                ('unp', models.TextField(blank=True, verbose_name='УНП')),
                ('title_qr', models.TextField(blank=True, verbose_name='Оплата с помощью QR-кода Cashew')),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to='payment_schemes/', verbose_name='QR photo Токен')),
            ],
            options={
                'verbose_name': 'ЕРИП платные услуги физ лицам',
                'verbose_name_plural': 'ЕРИП платные услуги физ лицам',
            },
        ),
    ]
