# Generated by Django 5.0.3 on 2024-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0227_enypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enypayment',
            name='title_qr',
            field=models.TextField(blank=True, verbose_name='Тайтл QR-кода Cashew'),
        ),
    ]
