# Generated by Django 5.0.3 on 2024-12-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0228_alter_enypayment_title_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticks',
            name='description_pdf',
            field=models.TextField(default='Описание для блоков с Файлами'),
        ),
        migrations.AddField(
            model_name='ticks',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/', verbose_name='Прикрепить PDF'),
        ),
    ]
