# Generated by Django 5.0.3 on 2024-12-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0229_ticks_description_pdf_ticks_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticks',
            name='name_block_pdf',
            field=models.CharField(default='Имя для блоков с Файлом', max_length=700),
        ),
    ]
