# Generated by Django 5.0.3 on 2024-12-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0230_ticks_name_block_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticks_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('description', models.TextField(default='Описание')),
                ('pdf_file', models.FileField(null=True, upload_to='pdfs/', verbose_name='Прикрепить PDF')),
            ],
            options={
                'verbose_name': 'Внимание клещи (Блок с файлами)',
                'verbose_name_plural': 'Внимание клещи (Блок с файлами)',
            },
        ),
    ]
