# Generated by Django 5.0.3 on 2024-12-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0231_ticks_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticks',
            name='description_pdf',
        ),
        migrations.RemoveField(
            model_name='ticks',
            name='name_block_pdf',
        ),
        migrations.RemoveField(
            model_name='ticks',
            name='pdf_file',
        ),
    ]
