# Generated by Django 5.0.3 on 2024-12-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0232_remove_ticks_description_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunoprophylaxistipical',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='immunoprophylaxistipical',
            name='description_two',
        ),
        migrations.RemoveField(
            model_name='immunoprophylaxistipical',
            name='name_three',
        ),
        migrations.RemoveField(
            model_name='immunoprophylaxistipical',
            name='name_two',
        ),
    ]
