# Generated by Django 5.0.3 on 2024-12-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0233_remove_immunoprophylaxistipical_description_three_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': 'Платные Услуги ФИЗ ЛИЦАМ - О проведении обязательных и внеочередных медицинских осмотров работающих', 'verbose_name_plural': 'Платные Услуги ФИЗ ЛИЦАМ - О проведении обязательных и внеочередных медицинских осмотров работающих'},
        ),
        migrations.RemoveField(
            model_name='epidemialogytipical',
            name='description2',
        ),
    ]
