# Generated by Django 5.0.3 on 2024-12-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0234_alter_studies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalresource',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Образовательные ресурсы', 'verbose_name_plural': 'Образовательные ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='up_organ_inf',
            options={'verbose_name': 'Вышестоящий Орган Информация (низ стр)', 'verbose_name_plural': 'Вышестоящий Орган Информация (низ стр)'},
        ),
    ]
