# Generated by Django 5.0.3 on 2025-01-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0235_alter_educationalresource_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Тайтл заглавный', max_length=1000)),
                ('desc', models.TextField(default='Описание под тайтл')),
            ],
            options={
                'verbose_name': 'СКП (блоки нна стр)',
                'verbose_name_plural': 'СКП (блоки нна стр)',
            },
        ),
    ]
