# Generated by Django 5.0.3 on 2025-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0236_skp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SKP',
        ),
        migrations.AddField(
            model_name='quarantine',
            name='desc_single_main',
            field=models.TextField(blank=True, default='Описание для Новостной страницы'),
        ),
        migrations.AddField(
            model_name='quarantine',
            name='name_single_main',
            field=models.CharField(default='Тайтл для Новостной страницы', max_length=500),
        ),
    ]
