# Generated by Django 5.0.3 on 2025-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0237_delete_skp_quarantine_desc_single_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine',
            name='name_single_main',
            field=models.CharField(default='Тайтл для Новостной страницы', max_length=1500),
        ),
    ]
