# Generated by Django 5.0.3 on 2025-01-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0238_alter_quarantine_name_single_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryRegistry',
        ),
        migrations.DeleteModel(
            name='EpidemSituations',
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
