# Generated by Django 5.0.3 on 2025-01-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0239_delete_countryregistry_delete_epidemsituations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='name_typical_violations',
        ),
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='number',
        ),
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='objects_control',
        ),
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='typical_violations',
        ),
        migrations.CreateModel(
            name='ControlNadzorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='Номер строки(ячейки в таблице)', max_length=350)),
                ('objects_control', models.TextField(default='Объекты контроля')),
                ('typical_violations', models.TextField(default='Типичные нарушения')),
                ('name_typical_violations', models.TextField(default='Наименования технических регламентов')),
                ('control_nadzor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='webapp.controlnadzortipical')),
            ],
        ),
    ]
