# Generated by Django 5.0.3 on 2025-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0240_remove_controlnadzortipical_name_typical_violations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImmunoprophylaxisInf',
        ),
        migrations.RenameField(
            model_name='immunoprophylaxistipical',
            old_name='description',
            new_name='description_single',
        ),
        migrations.AddField(
            model_name='immunoprophylaxistipical',
            name='desc_main_page',
            field=models.CharField(default='Описание для гл.страницы имунопрофилактика (в блок)', max_length=400),
        ),
        migrations.AddField(
            model_name='immunoprophylaxistipical',
            name='name_block',
            field=models.CharField(default='Тайтл для гл.страницы имунопрофилактика', max_length=350),
        ),
    ]
