# Generated by Django 5.0.3 on 2025-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0241_delete_immunoprophylaxisinf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlnadzortipical',
            name='description_for_all',
            field=models.TextField(default='Описание для всего'),
        ),
    ]
