# Generated by Django 5.0.3 on 2025-01-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0242_controlnadzortipical_description_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='description',
        ),
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='controlnadzortipical',
            name='description_two',
        ),
    ]
