# Generated by Django 5.0.3 on 2025-02-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0243_remove_controlnadzortipical_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name': '❤️ Избранное(первый блок на гл.,стр)', 'verbose_name_plural': '❤️ Избранное (первый блок на гл.,стр)'},
        ),
    ]
