# Generated by Django 5.0.3 on 2025-02-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0244_alter_featured_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelists',
            options={'verbose_name': '🔖 Прейскуранты', 'verbose_name_plural': '🔖 Прейскуранты'},
        ),
    ]
