# Generated by Django 5.0.3 on 2025-02-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0245_alter_pricelists_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistsfiz',
            options={'verbose_name': '🗃️ Доки для Физ лиц (нижний блок перед ерип)', 'verbose_name_plural': '🗃️ Доки для Физ лиц (нижний блок перед ерип)'},
        ),
    ]
