# Generated by Django 5.0.3 on 2025-02-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0246_alter_pricelistsfiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': '🏥ℹ️ Об Учреждении (блок с фото на гл.стр с описанием)', 'verbose_name_plural': '🏥ℹ️ Об Учреждении (блок с фото на гл.стр с описанием)'},
        ),
        migrations.AlterModelOptions(
            name='anticorr',
            options={'verbose_name': '👮📌 Антикоррупция (блоки PDF верх стр.)', 'verbose_name_plural': '👮📌 Антикоррупция (блоки PDF верх стр.)'},
        ),
        migrations.AlterModelOptions(
            name='anticorrtitle',
            options={'verbose_name': '👮📌 Антикоррупция ТАЙТЛ', 'verbose_name_plural': '👮📌 Антикоррупция ТАЙТЛ'},
        ),
        migrations.AlterModelOptions(
            name='book_complaint',
            options={'verbose_name': '📖 Книга жалоб и предложений', 'verbose_name_plural': '📖 Книга жалоб и предложений'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '👨🏻\u200d⚕️ Доктора', 'verbose_name_plural': '👨🏻\u200d⚕️ Доктора'},
        ),
        migrations.AlterModelOptions(
            name='duties',
            options={'verbose_name': '⚖️ Права и обязанности (тайтл и описание)', 'verbose_name_plural': '⚖️ Права и обязанности (тайтл и описание)'},
        ),
        migrations.AlterModelOptions(
            name='econimicsouz',
            options={'verbose_name': '🤝🇺🇳 Еврозийский экономичекский союз', 'verbose_name_plural': '🤝🇺🇳 Еврозийский экономичекский союз'},
        ),
        migrations.AlterModelOptions(
            name='educationalresource',
            options={'ordering': ['-pub_date'], 'verbose_name': '🎓 Образовательные ресурсы (блоки PDF верх стр.)', 'verbose_name_plural': '🎓 Образовательные ресурсы (блоки PDF верх стр.)'},
        ),
        migrations.AlterModelOptions(
            name='electronic_appeals_title_desc',
            options={'verbose_name': '👨\u200d💻 Электронные Обращения (тайтл и описание)', 'verbose_name_plural': '👨\u200d💻 Электронные Обращения (тайтл и описание)'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': '🎖️🧪 Экспертиза', 'verbose_name_plural': '🎖️🧪 Экспертиза'},
        ),
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name': '💹📌 График Приёма Заголовок и описание', 'verbose_name_plural': '💹📌 График Приёма Заголовок и описание'},
        ),
        migrations.AlterModelOptions(
            name='hotlinehours',
            options={'verbose_name': '☎️♨️ Прямая линия (таблица)', 'verbose_name_plural': '☎️♨️ Прямая линия (таблица)'},
        ),
        migrations.AlterModelOptions(
            name='hotlinehours_title',
            options={'verbose_name': '☎️♨️ Прямая линия тайтл и описание', 'verbose_name_plural': '☎️♨️ Прямая линия тайтл и описание'},
        ),
        migrations.AlterModelOptions(
            name='hotlinehours_title_desc',
            options={'verbose_name': '☎️♨️ Прямая линия Порядок проведения (тайтл и описание)', 'verbose_name_plural': '☎️♨️ Прямая линия Порядок проведения (тайтл и описание)'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryfruitvegetable',
            options={'verbose_name': '🙎\u200d♂️💳📌 Лабораторные исследования плодоовощной 🥗 продукции (ФИЗ ЛИЦАМ табл 3)', 'verbose_name_plural': '🙎\u200d♂️💳📌 Лабораторные исследования плодоовощной 🥗 продукции (ФИЗ ЛИЦАМ табл 3)'},
        ),
        migrations.AlterModelOptions(
            name='mainappeals',
            options={'verbose_name': '📧📢 Обращения главная стр.(тайтл и описание)', 'verbose_name_plural': '📧📢 Обращения главная стр.(тайтл и описание)'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': '📅⏰ Порядок и Сроки Обжалования (тайтл и описание)', 'verbose_name_plural': '📅⏰ Порядок и Сроки Обжалования (тайтл и описание)'},
        ),
        migrations.AlterModelOptions(
            name='normativedocuments',
            options={'verbose_name': '📝🗂️ Нормативные документы (инфо ссылка на pravo.by)', 'verbose_name_plural': '📝🗂️ Нормативные документы (инфо ссылка на pravo.by)'},
        ),
        migrations.AlterModelOptions(
            name='receptionhours',
            options={'verbose_name': '💹📌 Часы приема (таблица)', 'verbose_name_plural': '💹📌 Часы приема (таблица)'},
        ),
        migrations.AlterModelOptions(
            name='researches',
            options={'verbose_name': '🏥ℹ️ Об Учреждении Блок Исследования', 'verbose_name_plural': '🏥ℹ️ Об Учреждении Блок Исследования'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': '🛠️📌 Услуги (gif иконки, на стр.услуг и на главной стр.)', 'verbose_name_plural': '🛠️📌 Услуги (gif иконки, на стр.услуг и на главной стр.)'},
        ),
        migrations.AlterModelOptions(
            name='services_title',
            options={'verbose_name': '🛠️📌 Тайтл Услуги (блок с gif иконками, на стр.услуг и на главной стр.)', 'verbose_name_plural': '🛠️📌 Тайтл Услуги (блок с gif иконками, на стр.услуг и на главной стр.)'},
        ),
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': '🙎\u200d♂️💳📌 Платные Услуги ФИЗ ЛИЦАМ - осмотр работающих (табл 1)', 'verbose_name_plural': '🙎\u200d♂️💳📌 Платные Услуги ФИЗ ЛИЦАМ - осмотр работающих (табл 1)'},
        ),
        migrations.AlterModelOptions(
            name='up_organ_inf',
            options={'verbose_name': '🗼🏙️ Вышестоящий Орган (телефон горячей линии низ стр.)', 'verbose_name_plural': '🗼🏙️ Вышестоящий Орган (телефон горячей линии низ стр.)'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': '👔🔍 Вакансии', 'verbose_name_plural': '👔🔍 Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='waterqualitysafety',
            options={'verbose_name': '🙎\u200d♂️💳📌 Лабораторные исследования воды 🧪 на качество и безопасность ⚛︎🧬🧫 (ФИЗ ЛИЦАМ табл 2)', 'verbose_name_plural': '🙎\u200d♂️💳📌 Лабораторные исследования воды 🧪 на качество и безопасность ⚛︎🧬🧫 (ФИЗ ЛИЦАМ табл 2)'},
        ),
    ]
