# Generated by Django 5.0.3 on 2025-03-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0247_alter_aboutus_options_alter_anticorr_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthistory',
            options={'verbose_name': '🏥ℹ️ История - Описание (блоки на главной под фото) 🇩', 'verbose_name_plural': '🏥ℹ️ История - Описание (блоки на главной под фото) 🇩'},
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': '🏥ℹ️ Об Учреждении (блок с фото на гл.стр с описанием) 🇩', 'verbose_name_plural': '🏥ℹ️ Об Учреждении (блок с фото на гл.стр с описанием) 🇩'},
        ),
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name': '👦✔️ АП Кадровая Служба (таблица Бухгалтерия) 𝄜', 'verbose_name_plural': '👦✔️ АП Кадровая Служба (таблица Бухгалтерия) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='accountingdesc',
            options={'verbose_name': '👦✔️ АП Бухгалтерия (тайтл и описание) 🇹 | 🇩', 'verbose_name_plural': '👦✔️ АП Бухгалтерия (тайтл и описание) 🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '💡🗣️ Ответ', 'verbose_name_plural': '💡🗣️ Ответы'},
        ),
        migrations.AlterModelOptions(
            name='anticorrtitle',
            options={'verbose_name': '👮📌 Антикоррупция ТАЙТЛ  🇹 ', 'verbose_name_plural': '👮📌 Антикоррупция ТАЙТЛ  🇹 '},
        ),
        migrations.AlterModelOptions(
            name='blanksinventory',
            options={'verbose_name': '👦✔️ АП Бланки (перечень)', 'verbose_name_plural': '👦✔️ АП Бланки (перечень)'},
        ),
        migrations.AlterModelOptions(
            name='centrenews',
            options={'verbose_name': '📰🌐 Блок с новостями(зелено-красный)', 'verbose_name_plural': '📰🌐 Блок с новостями(зелено-красный)'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': '🏰🏋️ Здоровые города и поселки (Тайтл описание фото, добавить посёлок) 🇩', 'verbose_name_plural': '🏰🏋️ Здоровые города и поселки (Тайтл описание фото, добавить посёлок) 🇩'},
        ),
        migrations.AlterModelOptions(
            name='citiestitle',
            options={'verbose_name': '🏰🏋️ Здоровые города и поселки (Тайтл для блока Посёлка) 🇹', 'verbose_name_plural': '🏰🏋️ Здоровые города и поселки (Тайтл для блока Посёлка) 🇹'},
        ),
        migrations.AlterModelOptions(
            name='citydescription',
            options={'verbose_name': '🏰🏋️ Здоровые города и поселки - Интерактивная Доска', 'verbose_name_plural': '🏰🏋️ Здоровые города и поселки - Интерактивная Доска'},
        ),
        migrations.AlterModelOptions(
            name='cnadtipicalname',
            options={'verbose_name': '🕹️🧐 Конт/надзор деятельность Типичные нарушения (Тайтл) 🇹', 'verbose_name_plural': '🕹️🧐 Контрольно надзорная деятельность Типичные нарушения(Тайтл) 🇹'},
        ),
        migrations.AlterModelOptions(
            name='contactinfohad',
            options={'verbose_name': '📲🗺️ Контактная информация для Top Bar', 'verbose_name_plural': '📲🗺️ Контактная информация для Top Bar'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '📲🗺️ Контакты & данные', 'verbose_name_plural': '📲🗺️ Контакты & данные'},
        ),
        migrations.AlterModelOptions(
            name='controlnadzortipical',
            options={'verbose_name': '🕹️🧐 Конт/надзор деятельность Типичные нарушения(таблица) 𝄜', 'verbose_name_plural': '🕹️🧐 Контрольно надзорная деятельность Типичные нарушения(таблица) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='customproductsinf',
            options={'verbose_name': '🕹️🧐 Конт/надзор деятельность Нестандартная продукция 𝄜', 'verbose_name_plural': '🕹️🧐 Контрольно надзорная деятельность Нестандартная продукция(таблица) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='customproductsname',
            options={'verbose_name': '🕹️🧐 Конт/надзор деятельность Нестандартная продукция (Тайтл) 🇹', 'verbose_name_plural': '🕹️🧐 Контрольно надзорная деятельность Нестандартная продукция(Тайтл) 🇹'},
        ),
        migrations.AlterModelOptions(
            name='deratization',
            options={'verbose_name': '🧼🚩 Дератизация описание 🇩', 'verbose_name_plural': '🧼🚩 Дератизация описание 🇩'},
        ),
        migrations.AlterModelOptions(
            name='disinfection',
            options={'verbose_name': '🧼🚩 Дезинфекция главное 🇲 🇩', 'verbose_name_plural': '🧼🚩 Дезинфекция главное 🇲 🇩'},
        ),
        migrations.AlterModelOptions(
            name='disinfectiondesc',
            options={'verbose_name': '🧼🚩 Дезинфекция описание 🇩', 'verbose_name_plural': '🧼🚩 Дезинфекция описание 🇩'},
        ),
        migrations.AlterModelOptions(
            name='disinsection',
            options={'verbose_name': '🧼🚩 Дезинсекция описание 🇩', 'verbose_name_plural': '🧼🚩 Дезинсекция описание 🇩'},
        ),
        migrations.AlterModelOptions(
            name='duties',
            options={'verbose_name': '⚖️ Права и обязанности (тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '⚖️ Права и обязанности (тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='electronic_appeals_title_desc',
            options={'verbose_name': '👨\u200d💻 Электронные Обращения (тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '👨\u200d💻 Электронные Обращения (тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='enypayment',
            options={'verbose_name': '🪙💲 ЕРИП платные услуги физ лицам', 'verbose_name_plural': '🪙💲 ЕРИП платные услуги физ лицам'},
        ),
        migrations.AlterModelOptions(
            name='epidemialogyname',
            options={'verbose_name': '☣️😷 Эпидемиалогия (Тайтл) 🇹', 'verbose_name_plural': '☣️😷 Эпидемиалогия (Тайтл) 🇹'},
        ),
        migrations.AlterModelOptions(
            name='epidemialogytipical',
            options={'verbose_name': '☣️😷 Эпидемиалогия (статьи) 📜', 'verbose_name_plural': '☣️😷 Эпидемиалогия (статьи) 📜'},
        ),
        migrations.AlterModelOptions(
            name='erippayment',
            options={'verbose_name': '🪙💲 ЕРИП данные', 'verbose_name_plural': '🪙💲 ЕРИП данные'},
        ),
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name': '💹📌 График Приёма Заголовок и описание  🇹 | 🇩', 'verbose_name_plural': '💹📌 График Приёма Заголовок и описание  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='healthy',
            options={'ordering': ['-pub_date'], 'verbose_name': '🏰🏋️ Здоровые города и поселки (ФАЙЛЫ) 📁', 'verbose_name_plural': '🏰🏋️ Здоровые города и поселки (ФАЙЛЫ) 📁'},
        ),
        migrations.AlterModelOptions(
            name='healthytitle',
            options={'verbose_name': '🏰🏋️ Зд/Гор и поселки (Верхний ТАЙТЛ и ОПИСАНИЕ) 🇹 | 🇩', 'verbose_name_plural': '🏰🏋️ Здоровые города и поселки (Верхний ТАЙТЛ и ОПИСАНИЕ) 🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='hotlinehours',
            options={'verbose_name': '☎️♨️ Прямая линия (таблица) 𝄜', 'verbose_name_plural': '☎️♨️ Прямая линия (таблица) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='hotlinehours_title',
            options={'verbose_name': '☎️♨️ Прямая линия тайтл и описание  🇹 | 🇩', 'verbose_name_plural': '☎️♨️ Прямая линия тайтл и описание  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='hotlinehours_title_desc',
            options={'verbose_name': '☎️♨️ Прямая линия Порядок проведения (тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '☎️♨️ Прямая линия Порядок проведения (тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='humanresources',
            options={'verbose_name': '👦✔️ АП Кадровая Служба (таблица) 𝄜', 'verbose_name_plural': '👦✔️ АП Кадровая Служба (таблица) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='humanresourcesdesc',
            options={'verbose_name': '👦✔️ АП Кадровая Служба (название и описание)  🇹 | 🇩', 'verbose_name_plural': '👦✔️ АП Кадровая Служба (название и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='immunoprophylaxistipical',
            options={'verbose_name': '☣️😷 Иммунопрофилактика (статьи) 📜', 'verbose_name_plural': '☣️😷 Иммунопрофилактика (статьи) 📜'},
        ),
        migrations.AlterModelOptions(
            name='informationanalytical',
            options={'ordering': ['-pub_date'], 'verbose_name': '📜📊 Информационно-аналитический бюллетень', 'verbose_name_plural': '📜📊 Информационно-аналитический бюллетень'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '👦✔️ АП перечень', 'verbose_name_plural': '👦✔️ АП перечень'},
        ),
        migrations.AlterModelOptions(
            name='laboratories',
            options={'verbose_name': '💉☣  Лабораторные услуги (2ая половина) 🧪', 'verbose_name_plural': '💉☣  Лабораторные услуги (2ая половина) 🧪'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': '💉☣ Лабораторные услуги 🧪', 'verbose_name_plural': '💉☣ Лабораторные услуги 🧪'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryfruitvegetable',
            options={'verbose_name': '🧑\u200d🔬 Лабораторные исследования плод/овощ 🥗 продукции', 'verbose_name_plural': '🧑\u200d🔬 Лабораторные исследования плодоовощной 🥗 продукции (ФИЗ ЛИЦАМ табл 3) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='listingdecree',
            options={'verbose_name': '👦✔️ АП Указ (таблица) 𝄜', 'verbose_name_plural': '👦✔️ АП Указ (таблица) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='listingdecreedesc',
            options={'verbose_name': '👦✔️ АП Указ (в отношении граждан) 🇩', 'verbose_name_plural': '👦✔️ АП Указ (в отношении граждан) 🇩'},
        ),
        migrations.AlterModelOptions(
            name='mainappeals',
            options={'verbose_name': '📧📢 Обращения главная стр.(тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '📧📢 Обращения главная стр.(тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': '📅⏰ Порядок и Сроки Обжалования (тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '📅⏰ Порядок и Сроки Обжалования (тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='monitoringplan',
            options={'verbose_name': '📊 План Мониторинга 🇲 🇹 🇩', 'verbose_name_plural': '📊 План Мониторинга 🇲 🇹 🇩'},
        ),
        migrations.AlterModelOptions(
            name='monitoringplanarkhive',
            options={'verbose_name': '📊 План Мониторинга Архив 🗄️🇹 🇩', 'verbose_name_plural': '📊 План Мониторинга Архив 🗄️🇹 🇩'},
        ),
        migrations.AlterModelOptions(
            name='normativedoc',
            options={'verbose_name': '📝🗂️ Нормативные документы (описание и файлы) 🇩', 'verbose_name_plural': '📝🗂️ Нормативные документы (описание и файлы) 🇩'},
        ),
        migrations.AlterModelOptions(
            name='objectives',
            options={'verbose_name': '🎯📈 Цели устойчивого развития', 'verbose_name_plural': '🎯📈 Цели устойчивого развития'},
        ),
        migrations.AlterModelOptions(
            name='organ_title_desc',
            options={'verbose_name': '🧑\u200d⚖️ Вышестоящий орган (тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '🧑\u200d⚖️ Вышестоящий орган (тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='ourpartners',
            options={'verbose_name': '🧑\u200d🦲 Слайдер Партнеры', 'verbose_name_plural': '🧑\u200d🦲 Слайдер Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='photoday',
            options={'verbose_name': '🖼️ Фото дня', 'verbose_name_plural': '🖼️ Фото дня'},
        ),
        migrations.AlterModelOptions(
            name='profsouz',
            options={'verbose_name': '🏥👩🏿\u200d⚕️ О центре Профсоюз таблицы с сотрудниками 𝄜', 'verbose_name_plural': '🏥👩🏿\u200d⚕️ О центре Профсоюз таблицы с сотрудниками 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='profsouzdesc',
            options={'verbose_name': '🏥👩🏿\u200d⚕️  О центре Профсоюз верхнее описание 🇩', 'verbose_name_plural': '🏥👩🏿\u200d⚕️  О центре Профсоюз верхнее описание 🇩'},
        ),
        migrations.AlterModelOptions(
            name='profsouzdescone',
            options={'verbose_name': '🏥👩🏿\u200d⚕️ О центре Профсоюз описание таблицы 𝄜', 'verbose_name_plural': '🏥👩🏿\u200d⚕️ О центре Профсоюз таблицы 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='profsouzicons',
            options={'verbose_name': '🏥👩🏿\u200d⚕️ О центре Профсоюз Иконки', 'verbose_name_plural': '🏥👩🏿\u200d⚕️ О центре Профсоюз Иконки'},
        ),
        migrations.AlterModelOptions(
            name='profsouztwo',
            options={'verbose_name': '🏥👩🏿\u200d⚕️  О центре Профсоюз таб/сотрудник (таблица 2) 𝄜', 'verbose_name_plural': '🏥👩🏿\u200d⚕️  О центре Профсоюз таблицы с сотрудниками (таблица 2) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='quarantine',
            options={'verbose_name': '🏥😷 Санитарно - Карантинные пункты (блоки )', 'verbose_name_plural': '🏥😷 Санитарно - Карантинные пункты (блоки)'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '❓❓❓  Вопросы', 'verbose_name_plural': '❓❓❓ Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='question_ansver_title',
            options={'verbose_name': '💡🗣️ Заголовок и Описание Ответов  🇹 | 🇩', 'verbose_name_plural': '💡🗣️ Заголовок и Описание Ответов  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='receptionhours',
            options={'verbose_name': '💹📌 Часы приема (таблица) 𝄜', 'verbose_name_plural': '💹📌 Часы приема (таблица) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': '📓✔️ АП Регистрация (перечень) 🇩', 'verbose_name_plural': '📓✔️ АП Регистрация (перечень) 🇩'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': '👦✔️ АП в отношении граждан (тайтл и описание)  🇹 | 🇩', 'verbose_name_plural': '👦✔️ АП в отношении граждан (тайтл и описание)  🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='services_title',
            options={'verbose_name': '🛠️📌 Тайтл Услуги (блок с gif иконками, на стр.услуг и на главной стр.) 🇹 ', 'verbose_name_plural': '🛠️📌 Тайтл Услуги (блок с gif иконками, на стр.услуг и на главной стр.)  🇹 '},
        ),
        migrations.AlterModelOptions(
            name='serviceslawyername',
            options={'verbose_name': '🪙💲 Пл услуги Юр лицам и ИП (Тайтл)', 'verbose_name_plural': '🪙💲 Пл услуги Юр лицам и ИП (Тайтл)'},
        ),
        migrations.AlterModelOptions(
            name='serviceslawyertipical',
            options={'verbose_name': '🪙💲 Пл услуги Юр лицам и ИП (статьи)', 'verbose_name_plural': '🪙💲 Пл услуги Юр лицам и ИП (статьи)'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': '🧬 Структура 👩🏻\u200d🔬⚗️🧪🥼', 'verbose_name_plural': '🧬 Структура 👩🏻\u200d🔬⚗️🧪🥼'},
        ),
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': '🧑\u200d🔬 Платные Услуги ФИЗ ЛИЦАМ - осмотр работающих таб1 𝄜', 'verbose_name_plural': '🧑\u200d🔬 Платные Услуги ФИЗ ЛИЦАМ - осмотр работающих (табл 1) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='ticks',
            options={'verbose_name': '⚠️🪲 Внимание клещи', 'verbose_name_plural': '⚠️🪲 Внимание клещи'},
        ),
        migrations.AlterModelOptions(
            name='ticks_files',
            options={'verbose_name': '⚠️🪲 Внимание клещи (Блок с файлами) 📁', 'verbose_name_plural': '⚠️🪲 Внимание клещи (Блок с файлами) 📁'},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'verbose_name': '👦✔️ АП Профсоюз 𝄜 (таблица)', 'verbose_name_plural': '👦✔️ АП Профсоюз 𝄜 (таблица)'},
        ),
        migrations.AlterModelOptions(
            name='uniondesc',
            options={'verbose_name': '👦✔️ АП Профсоюз (тайтл и описание) 🇹 | 🇩', 'verbose_name_plural': '👦✔️ АП Профсоюз (тайтл и описание) 🇹 | 🇩'},
        ),
        migrations.AlterModelOptions(
            name='up_organ',
            options={'verbose_name': '🧑\u200d⚖️ Вышестоящий орган 𝄜 (таблица)', 'verbose_name_plural': '🧑\u200d⚖️ Вышестоящий орган 𝄜 (таблица)'},
        ),
        migrations.AlterModelOptions(
            name='waterqualitysafety',
            options={'verbose_name': '🧑\u200d🔬 Лабораторные исследования воды 🧪 на качество ⚛︎🧬🧫', 'verbose_name_plural': '🧑\u200d🔬 Лабораторные исследования воды 🧪 на качество и безопасность ⚛︎🧬🧫 (ФИЗ ЛИЦАМ табл 2) 𝄜'},
        ),
        migrations.AlterModelOptions(
            name='zoj',
            options={'verbose_name': '🤸\u200d♂️🏀 Здоровый Образ Жизни', 'verbose_name_plural': '🤸\u200d♂️🏀 Здоровый Образ Жизни'},
        ),
    ]
