# Generated by Django 5.0.3 on 2025-03-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0248_alter_abouthistory_options_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_be',
            field=models.TextField(default='About Us Description One', null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(default='About Us Description One', null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(default='About Us Description One', null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_be',
            field=models.CharField(default='About Us Name One', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_en',
            field=models.CharField(default='About Us Name One', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_ru',
            field=models.CharField(default='About Us Name One', max_length=100, null=True),
        ),
    ]
