# Generated by Django 5.0.3 on 2025-03-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0249_aboutus_description_be_aboutus_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='description_be',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name_be',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='description_be',
            field=models.TextField(default='Description', null=True),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='description_en',
            field=models.TextField(default='Description', null=True),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='description_ru',
            field=models.TextField(default='Description', null=True),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
