# Generated by Django 5.0.3 on 2025-03-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0250_remove_aboutus_description_be_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Busel', max_length=50)),
                ('photo_busel', models.ImageField(blank=True, null=True, upload_to='busel/')),
            ],
            options={
                'verbose_name': 'Бусел (фото)',
                'verbose_name_plural': 'Бусел (фото)',
            },
        ),
        migrations.RemoveField(
            model_name='abouthistory',
            name='description_be',
        ),
        migrations.RemoveField(
            model_name='abouthistory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='abouthistory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='abouthistory',
            name='name_be',
        ),
        migrations.RemoveField(
            model_name='abouthistory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='abouthistory',
            name='name_ru',
        ),
    ]
