# Generated by Django 5.0.3 on 2025-03-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0251_busel_remove_abouthistory_description_be_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busel',
            options={'verbose_name': '🐦🐥 Бусел (фото)', 'verbose_name_plural': '🐦🐥 Бусел (фото)'},
        ),
    ]
