# Generated by Django 5.0.3 on 2025-04-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0252_alter_busel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name Slider', max_length=300)),
            ],
            options={
                'verbose_name': '🎞️ 🖼️ Главный Слайдер',
                'verbose_name_plural': '🎞️ 🖼️ Главный Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок слайда')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='webapp.slidermain')),
            ],
            options={
                'verbose_name': '🎞️ 🖼️ Слайд',
                'verbose_name_plural': '🎞️ 🖼️ Слайды',
                'ordering': ['order'],
            },
        ),
    ]
