# Generated by Django 5.0.3 on 2025-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0253_slidermain_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryfruitvegetable',
            name='cost_info',
            field=models.CharField(default='Цена указана по состоянию на:', max_length=500),
        ),
    ]
